# Evaluating your SAE

Code based off Rob Graham's ([themachinefan](https://github.com/themachinefan)) SAE evaluation code.

In [1]:
import os
os.getcwd()

'/workspace/ViT-Prisma/src/vit_prisma/sae/evals'

In [2]:
import einops
import torch
import torchvision

import plotly.express as px

from tqdm import tqdm

import numpy as np
import os
import requests

# Setup

In [3]:
from dataclasses import dataclass
from vit_prisma.sae.config import VisionModelSAERunnerConfig


# sparse-autoencoder-clip-b-32-sae-vanilla-x64-layer-11-hook_resid_post-l1-0.0001
# sparse-autoencoder-clip-b-32-sae-vanilla-x64-layer-10-hook_mlp_out-l1-0.0001
# sparse-autoencoder-clip-b-32-sae-vanilla-x64-layer-0-hook_mlp_out-l1-0.0001
# sparse-autoencoder-clip-b-32-sae-vanilla-x64-layer-0-hook_resid_post-l1-0.0001
# !! Change hook point - it is *not* changed automatically
# sparse-autoencoder-clip-b-32-sae-vanilla-x64-layer-11-hook_resid_post-l1-0.0001/n_images_2600058.pt
selected_sae_weights = "sae-top_k-64-cls_only-layer_11-hook_resid_post/weights.pt"


@dataclass
class EvalConfig(VisionModelSAERunnerConfig):
    sae_path: str = f'/workspace/sae_checkpoints/{selected_sae_weights}'
    model_name: str = "open-clip:laion/CLIP-ViT-B-32-DataComp.XL-s13B-b90K"
    model_type: str =  "clip"
    patch_size: str = 32

    dataset_path = "/workspace"
    dataset_train_path: str = "/workspace/ILSVRC/Data/CLS-LOC/train"
    dataset_val_path: str = "/workspace/ILSVRC/Data/CLS-LOC/val"

    verbose: bool = True

    device: bool = 'cuda'

    eval_max: int = 50_000 # 50_000
    batch_size: int = 32
        
#     hook_point_layer: int = 11
    # make the max image output folder a subfolder of the sae path


    @property
    def max_image_output_folder(self) -> str:
        # Get the base directory of sae_checkpoints
        sae_base_dir = os.path.dirname(os.path.dirname(self.sae_path))
        
        # Get the name of the original SAE checkpoint folder
        sae_folder_name = os.path.basename(os.path.dirname(self.sae_path))
        
        # Create a new folder path in sae_checkpoints/images with the original name
        output_folder = os.path.join(sae_base_dir, 'max_images', sae_folder_name)
        output_folder = os.path.join(output_folder, f"layer_{self.hook_point_layer}") # Add layer number

        
        # Ensure the directory exists
        os.makedirs(output_folder, exist_ok=True)
        
        return output_folder

cfg = EvalConfig()

n_tokens_per_buffer (millions): 0.032
Lower bound: n_contexts_per_buffer (millions): 0.00064
Total training steps: 158691
Total training images: 13000000
Total wandb updates: 15869
Expansion factor: 16
n_tokens_per_feature_sampling_window (millions): 204.8
n_tokens_per_dead_feature_window (millions): 1024.0
Using Ghost Grads.
We will reset the sparsity calculation 158 times.
Number tokens in sparsity calculation window: 4.10e+06
Gradient clipping with max_norm=1.0
Using SAE initialization method: encoder_transpose_decoder


In [4]:
torch.set_grad_enabled(False)

## Load model

In [5]:
from vit_prisma.models.base_vit import HookedViT

model_name = "open-clip:laion/CLIP-ViT-B-32-DataComp.XL-s13B-b90K"
model = HookedViT.from_pretrained(model_name, is_timm=False, is_clip=True).to(cfg.device)
 

model_id download_pretrained_from_hf: laion/CLIP-ViT-B-32-DataComp.XL-s13B-b90K
Official model name open-clip:laion/CLIP-ViT-B-32-DataComp.XL-s13B-b90K
Converting OpenCLIP weights
model_id download_pretrained_from_hf: laion/CLIP-ViT-B-32-DataComp.XL-s13B-b90K
visual projection shape torch.Size([768, 512])
Setting center_writing_weights to False for OpenCLIP
Setting fold_ln to False for OpenCLIP
Loaded pretrained model open-clip:laion/CLIP-ViT-B-32-DataComp.XL-s13B-b90K into HookedTransformer


## Load datasets

In [6]:
import importlib
import vit_prisma
# importlib.reload(vit_prisma.dataloaders.imagenet_dataset)

In [7]:
# load dataset
import open_clip
from vit_prisma.utils.data_utils.imagenet_utils import setup_imagenet_paths
from vit_prisma.dataloaders.imagenet_dataset import get_imagenet_transforms_clip, ImageNetValidationDataset

from torchvision import transforms
from transformers import CLIPProcessor

og_model_name = "hf-hub:laion/CLIP-ViT-B-32-DataComp.XL-s13B-b90K"
og_model, _, preproc = open_clip.create_model_and_transforms(og_model_name)
processor = preproc

size=224

data_transforms = transforms.Compose([
    transforms.Resize((size, size)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.48145466, 0.4578275, 0.40821073],
                     std=[0.26862954, 0.26130258, 0.27577711]),
])
    
imagenet_paths = setup_imagenet_paths(cfg.dataset_path)
imagenet_paths["train"] = "/workspace/ILSVRC/Data/CLS-LOC/train"
imagenet_paths["val"] = "/workspace/ILSVRC/Data/CLS-LOC/val"
imagenet_paths["val_labels"] = "/workspace/LOC_val_solution.csv"
imagenet_paths["label_strings"] = "/workspace/LOC_synset_mapping.txt"
print()
train_data = torchvision.datasets.ImageFolder(cfg.dataset_train_path, transform=data_transforms)
val_data = ImageNetValidationDataset(cfg.dataset_val_path, 
                                imagenet_paths['label_strings'], 
                                imagenet_paths['val_labels'], 
                                data_transforms,
                                return_index=True,
)
val_data_visualize = ImageNetValidationDataset(cfg.dataset_val_path, 
                                imagenet_paths['label_strings'], 
                                imagenet_paths['val_labels'],
                                torchvision.transforms.Compose([
    torchvision.transforms.Resize((224, 224)),
    torchvision.transforms.ToTensor(),]), return_index=True)

print(f"Validation data length: {len(val_data)}") if cfg.verbose else None



Validation data length: 50000


In [8]:
from vit_prisma.sae.training.activations_store import VisionActivationsStore
# import dataloader
from torch.utils.data import DataLoader

# activations_loader = VisionActivationsStore(cfg, model, train_data, eval_dataset=val_data)
val_dataloader = DataLoader(val_data, batch_size=cfg.batch_size, shuffle=False, num_workers=4)


## Load pretrained SAE to evaluate

In [9]:
from vit_prisma.sae.sae import SparseAutoencoder
sparse_autoencoder = SparseAutoencoder(cfg).load_from_pretrained(f"/workspace/sae_checkpoints/{selected_sae_weights}")
sparse_autoencoder.to(cfg.device)
sparse_autoencoder.eval()  # prevents error if we're expecting a dead neuron mask for who 

# topk config needs editing for this to work

get_activation_fn received: activation_fn=relu, kwargs={}
n_tokens_per_buffer (millions): 0.00064
Lower bound: n_contexts_per_buffer (millions): 0.00064
Total training steps: 158691
Total training images: 650000000
Total wandb updates: 1586
Expansion factor: 64
n_tokens_per_feature_sampling_window (millions): 4.096
n_tokens_per_dead_feature_window (millions): 20.48
We will reset the sparsity calculation 158 times.
Number tokens in sparsity calculation window: 4.10e+06
Gradient clipping with max_norm=1.0
Using SAE initialization method: encoder_transpose_decoder
get_activation_fn received: activation_fn=topk, kwargs={'k': 64}


SparseAutoencoder(
  (hook_sae_in): HookPoint()
  (hook_hidden_pre): HookPoint()
  (hook_hidden_post): HookPoint()
  (hook_sae_out): HookPoint()
  (activation_fn): TopK(
    (postact_fn): ReLU()
  )
)

## Clip Labeling AutoInterp

In [10]:
# all_imagenet_class_names

In [11]:
from vit_prisma.dataloaders.imagenet_dataset import get_imagenet_index_to_name
ind_to_name = get_imagenet_index_to_name()

all_imagenet_class_names = []
for i in range(len(ind_to_name)):
    all_imagenet_class_names.append(ind_to_name[str(i)][1])

In [12]:
cfg.max_image_output_folder

'/workspace/sae_checkpoints/max_images/sae-top_k-64-cls_only-layer_11-hook_resid_post/layer_9'

## Feature steering

In [13]:
# Are these missing ReLU?
# A: No, relu is in encode_* which is run as part of normal sae forward.
# topk runs as usual
def steering_hook_fn_cls_only(
    activations, cfg, hook, sae, steering_indices, steering_strength=1.0, mean_ablation_values=None, include_error=False

):
    sae.to(activations.device)


    sae_input = activations.clone()
    sae_output, feature_activations, *data = sae(sae_input)
    
    steered_feature_activations = feature_activations.clone()
    
    # batch, stream, feats
    # cls token is *last* in sequence
    steered_feature_activations[:, 0, steering_indices] = steering_strength

    steered_sae_out = einops.einsum(
                steered_feature_activations,
                sae.W_dec,
                "... d_sae, d_sae d_in -> ... d_in",
            ) + sae.b_dec

    steered_sae_out = sae.run_time_activation_norm_fn_out(steered_sae_out)
    
    # print(f"steering norm: {(steered_sae_out - sae_output).norm()}")
#     print(f"L0 norm of feats: {torch.norm(feature_activations, p=0.0)}")
#     print(f"torch.where(feature_activations < 0, 1, 0).sum(): {torch.where(feature_activations < 0, 1, 0).sum()}")
    

    if include_error:
        error = sae_input - sae_output
        # print(f"error.norm(): {error.norm()}")
        return steered_sae_out + error
    return steered_sae_out


def steering_hook_fn(
    activations, cfg, hook, sae, steering_indices, steering_strength=1.0, mean_ablation_values=None, include_error=False

):
    sae.to(activations.device)


    sae_input = activations.clone()
    sae_output, feature_activations, *data = sae(sae_input)
    
    steered_feature_activations = feature_activations.clone()
    
    steered_feature_activations[:, :, steering_indices] = steering_strength

    steered_sae_out = einops.einsum(
                steered_feature_activations,
                sae.W_dec,
                "... d_sae, d_sae d_in -> ... d_in",
            ) + sae.b_dec

    steered_sae_out = sae.run_time_activation_norm_fn_out(steered_sae_out)
    
    # print(f"steering norm: {(steered_sae_out - sae_output).norm()}")
    
    

    if include_error:
        error = sae_input - sae_output
        # print(f"error.norm(): {error.norm()}")
        return steered_sae_out + error
    return steered_sae_out

In [14]:
random_feat_idxs = np.random.randint(0, high=sparse_autoencoder.b_enc.shape[0], size=(100))
# random_feat_idxs[0] = 655
# random_feat_idxs[1] = 656
# random_feat_idxs[2] = 665
# random_feat_idxs[3] = 2541

In [15]:
# for a given feature, set it high/low on maxim activ. imgs and high/low on non-activ images
# hook SAE and replace desired feature with 0 or 1 
from typing import List, Dict, Tuple
import torch
import einops
from tqdm import tqdm

from functools import partial

@torch.no_grad()
def compute_feature_activations_set_feat(
    images: torch.Tensor,
    model: torch.nn.Module,
    sparse_autoencoder: torch.nn.Module,
    encoder_weights: torch.Tensor,
    encoder_biases: torch.Tensor,
    feature_ids: List[int],
    feature_categories: List[str],
    top_k: int = 10,
    steering_strength: float = 10.0
):
    """
    Compute the highest activating tokens for given features in a batch of images.
    
    Args:
        images: Input images
        model: The main model
        sparse_autoencoder: The sparse autoencoder
        encoder_weights: Encoder weights for selected features
        encoder_biases: Encoder biases for selected features
        feature_ids: List of feature IDs to analyze
        feature_categories: Categories of the features
        top_k: Number of top activations to return per feature

    Returns:
        Dictionary mapping feature IDs to tuples of (top_indices, top_values)
    """
    
    
    # "blocks.11.hook_resid_post"
    # "blocks.0.hook_mlp_out"
    # "blocks.10.hook_mlp_out"
    hook_point_local = "blocks.11.hook_resid_post"
        
    
    recons_image_embeddings_feat_altered_list = []
    for idx in np.array(range(sparse_autoencoder.W_dec.shape[0]))[random_feat_idxs]:
        # steering_hook_fn, steering_hook_fn_cls_only
        steering_hook = partial(
            steering_hook_fn,
            cfg=cfg,
            sae=sparse_autoencoder,
            steering_indices=[idx],
            steering_strength=steering_strength,
            mean_ablation_values = [1.0],
            include_error=True,
            )
        
        
        recons_image_embeddings_feat_altered = model.run_with_hooks(
            images,
            fwd_hooks=[(hook_point_local, steering_hook)],
        )
        recons_image_embeddings_feat_altered_list.append(recons_image_embeddings_feat_altered)

    
    # output is in clip embedding space
    recons_image_embeddings_default = model.run_with_hooks(
        images,
        fwd_hooks=[(hook_point_local, lambda x, hook: x)],
    )
    
#     print(f"recons_image_embeddings_default: {recons_image_embeddings_default}")
#     print(f"recons_image_embeddings_default.shape: {recons_image_embeddings_default.shape}")
#     print(f"recons_image_embeddings_default: {recons_image_embeddings_default.shape}")

#     print(f"recons_image_embeddings_feat_altered: {recons_image_embeddings_feat_altered}")
#     print(f"recons_image_embeddings_feat_altered.shape: {recons_image_embeddings_feat_altered.shape}")

    return recons_image_embeddings_feat_altered_list, recons_image_embeddings_default

In [16]:
import torch
from PIL import Image

from collections import defaultdict
max_samples = cfg.eval_max

encoder_biases = sparse_autoencoder.b_enc#[interesting_features_indices]
encoder_weights = sparse_autoencoder.W_enc#[:, interesting_features_indices]

steering_strengths = [0.0, 5.0, 10.0, 20.0, 50.0, 150.0]#, 500.0, 1000.0, 2000.0, 5000.0, 10000.0]#, -200.0, -300.0]
# steering_strengths = [0.0, 5.0, 10.0, 20.0, 50.0, 150.0]#, 300.0]#, 500.0, 1000.0, 2000.0, 5000.0, 10000.0]#, -200.0, -300.0]


# these two things need to be pickled and documented well
# they cache run results
steering_strength_image_results = defaultdict(dict)
steering_strength_info = {}

og_model.cuda()




for steering_strength in steering_strengths:
    print(f"{'==============' * 2} steering_strength: {steering_strength} {'==============' * 2}")
    # ===== Get Steered and Default CLIP Outputs =====
    top_k=10
    processed_samples = 0
    default_embeds_list = []
    feature_steered_embeds = defaultdict(list)
    l = 0
    
    # remove tqdm
    for batch_images, _, batch_indices in tqdm(val_dataloader, total=max_samples // cfg.batch_size):
        batch_images = batch_images.to(cfg.device)
        batch_indices = batch_indices.to(cfg.device)
        batch_size = batch_images.shape[0]

        altered_embeds_list, default_embeds = compute_feature_activations_set_feat(
            batch_images, model, sparse_autoencoder, encoder_weights, encoder_biases,
            None, None, top_k, steering_strength
        )
        default_embeds_list.append(default_embeds)
        for j, altered_embeds in enumerate(altered_embeds_list):
            feature_steered_embeds[random_feat_idxs[j]].extend(altered_embeds)
        # either label embeds or optimize to maximal token in text transformer embedding face
        l += 1
        if l >= 5:
            break    
    default_embeds = torch.cat(default_embeds_list)
    
    with open("/workspace/clip_dissect_raw.txt", "r") as f:
        larger_vocab = [line[:-1] for line in f.readlines()][:5000]


    # ===== CLIP Embeds =====
    # use clip vocab here and compare embeds
    tokenizer = open_clip.get_tokenizer('ViT-B-32')
    text = tokenizer(larger_vocab)
    text_features = og_model.encode_text(text.cuda())
    text_features_normed = text_features/text_features.norm(dim=-1, keepdim=True)


    print(f"text_features_normed.shape: {text_features_normed.shape}")
    text_probs_altered_list = []
    with torch.no_grad(), torch.cuda.amp.autocast():
        for key in feature_steered_embeds:
            print(key)
            # embeds already have L2 norm of 1
            text_probs_altered = (100.0 * torch.stack(feature_steered_embeds[key]) @ text_features_normed.T).softmax(dim=-1)
            text_probs_altered_list.append(text_probs_altered)
        text_probs_default = (100.0 * default_embeds @ text_features_normed.T).softmax(dim=-1)

#     print("Label probs altered:", text_probs_altered.shape)  # prints: [[1., 0., 0.]]
#     print("Label probs default:", text_probs_default.shape)  # prints: [[1., 0., 0.]]
    
    
    # INVESTIGATE DOUBLE SOFTMAX POSSIBILITY
    
    # ===== Logit Difference =====
    # indexed as such in steering_strength_image_results:
    # per steering strength
    # per feature
    # per image
    
    selected_vocab = larger_vocab

    top_concept_per_feat = {}
    top_val_per_feat = {}
    top_diff_per_feat = {}
    steerability_per_feat = {}
    steerability_dir_per_feat = {}
    top_ratio_per_feat = {}
    
    # run this for sampled features over all of imagenet eval
    for j, text_probs_altered in enumerate(text_probs_altered_list):
        print(f"{'============================================'*2}\n\nFor Feature {random_feat_idxs[j]}")
#         print("actual image content:")
        default_vals_softmax, default_idxs_softmax = torch.topk(text_probs_default,k=10)
#         print(default_vals_softmax, "\n", np.array(selected_vocab)[default_idxs_softmax.cpu()])

        # this is for polysemanticity metric:
        # aggregate_prob_difference = (text_probs_altered - text_probs_default).mean(dim=0)
        # print(torch.topk(aggregate_prob_difference, k=10))
        # res = aggregate_prob_difference @ text_features_normed
        # diff = res - text_features_normed.sum(dim=0)/text_features_normed.sum(dim=0).norm(p=2.0)
        # print(diff.shape, diff.norm(p=2.0))
        # furthest_feats.append((diff.norm(p=2.0), feat, torch.topk(aggregate_prob_difference, k=10)))

        logit_diff = text_probs_altered - text_probs_default
#         logit_diff_aggregate = logit_diff.sum(dim=0)
        logit_diff_aggregate = logit_diff.mean(dim=0)
    
#         print(f"logit_diff.shape: {logit_diff.shape}")
#         print(f"logit_diff: {logit_diff}")
        steerability_score = torch.square(logit_diff_aggregate)
        steerability_directional = torch.mul(logit_diff_aggregate, torch.abs(logit_diff_aggregate))
#         print(f"steerability_score.shape: {steerability_score.shape}")
#         print(f"steerability_score: {steerability_score}")
#         print(f"steerability_directional.shape: {steerability_directional.shape}")
#         print(f"steerability_score: {steerability_directional}")
#         steerability_score_aggregate = steerability_score.mean(dim=0)
#         print(f"steerability_score_aggregate.shape: {steerability_score_aggregate.shape}")
#         print(f"steerability_score_aggregate: {steerability_score_aggregate}")
        

        # AHEM these are not logits - these are probabilities
        logit_ratio = text_probs_altered/text_probs_default
        logit_ratio_aggregate = logit_ratio.mean(dim=0)

        print(f"text_probs_altered shape: {text_probs_altered.shape}")
#         print(f"text_probs_altered.softmax(1) shape: {text_probs_altered.softmax(1).shape}")
        text_probs_altered_softmax = text_probs_altered#.softmax(1)
        vals_softmax, idxs_softmax = torch.topk(text_probs_altered_softmax,k=10)

    #     print(f"text_probs_altered.softmax(): {text_probs_altered.sum(0).softmax(0).shape}")
    #     text_probs_altered_softmax_agg = text_probs_altered.sum(0).softmax(0)
    #     vals_softmax_agg, idxs_softmax_agg = torch.topk(text_probs_altered_softmax_agg,k=10)

#         print(f"\nSoftmax Over {text_probs_altered.shape[0]} Images:\n{vals_softmax}")
#         print(np.array(selected_vocab)[idxs_softmax.cpu()])
#         for i in range(vals_softmax.shape[0]):
#             print(vals_softmax[i], "\n", np.array(selected_vocab)[idxs_softmax.cpu()][i])
#             break

    #     print(f"\nAgg Softmax Over {text_probs_altered.shape[0]} Images:\n{vals_softmax_agg}")
    #     print(np.array(selected_vocab)[idxs_softmax_agg.cpu()])

        vals_agg, idxs_agg = torch.topk(logit_diff_aggregate,k=10)
        vals_least_agg, idxs_least_agg = torch.topk(logit_diff_aggregate,k=10,largest=False)

        ratios_agg, ratios_idxs_agg = torch.topk(logit_ratio_aggregate,k=10)
        ratios_least_agg, ratios_idxs_least_agg = torch.topk(logit_ratio_aggregate,k=10,largest=False)

        vals, idxs = torch.topk(logit_diff,k=5)
        vals_least, idxs_least = torch.topk(logit_diff,k=5,largest=False)

        ratios, ratios_idxs = torch.topk(logit_ratio,k=5)
        ratios_least, ratios_idxs_least = torch.topk(logit_ratio,k=5,largest=False)

        # random_feat_idxs[j] is the index of the feature
        for img_idx in range(batch_images.shape[0]):
            if random_feat_idxs[j] not in steering_strength_image_results[str(steering_strength)].keys():
                steering_strength_image_results[str(steering_strength)][random_feat_idxs[j].copy()] = []
            # entries are torch.topk(k=10) results
            steering_strength_image_results[str(steering_strength)][random_feat_idxs[j]].append((np.array(selected_vocab, copy=True)[idxs_softmax.cpu()][img_idx], torch.clone(vals_softmax[img_idx])))
        
        # per image
        top_concept_per_feat[random_feat_idxs[j]] = np.array(selected_vocab)[idxs_softmax.cpu()][0][0]
        top_val_per_feat[random_feat_idxs[j]] = vals_softmax[0][0]
        
        # aggregate
        steerability_per_feat[random_feat_idxs[j]] = steerability_score
        steerability_dir_per_feat[random_feat_idxs[j]] = steerability_directional
        top_diff_per_feat[random_feat_idxs[j]] = vals_agg[0]
        top_ratio_per_feat[random_feat_idxs[j]] = ratios_agg[0]


        print(f"\nMost Changed, by Absolute Diff Over {logit_diff.shape[0]} Images:\n{vals_agg}")
        print(np.array(selected_vocab)[idxs_agg.cpu()])
#         print(vals_least_agg)
#         print(np.array(selected_vocab)[idxs_least_agg.cpu()])

        print(f"\nMost Changed, by Ratio Over {logit_diff.shape[0]} Images:")
        print(ratios_agg)
        print(np.array(selected_vocab)[ratios_idxs_agg.cpu()])
#         print(ratios_least_agg)
#         print(np.array(selected_vocab)[ratios_idxs_least_agg.cpu()])
    
    steering_strength_info[steering_strength] = (top_concept_per_feat,top_val_per_feat,top_ratio_per_feat,top_diff_per_feat,steerability_per_feat,steerability_dir_per_feat)


============================ steering_strength: 0.0 ============================


  0%|▎                                                                                                 | 4/1562 [00:30<3:16:25,  7.56s/it]


text_features_normed.shape: torch.Size([5000, 512])
26600
8518
16347
46981
44837
41588
46158
30052
36177
17551
35377
41389
12950
7623
48170
1527
22666
45420
36780
38339
22534
32663
2032
7697
23439
18977
1366
36950
44476
9108
42357
33482
2874
24884
17589
21462
561
5473
9246
7131
21158
13913
2705
21193
1807
48735
25174
13982
26171
4525
2722
31039
31221
9728
5823
253
24617
20914
30159
14840
3193
2490
39796
31782
33170
4333
26182
23970
21597
3031
15968
5767
45594
47466
34121
18305
7995
42826
19049
9407
3818
47779
44957
40803
41756
38695
38400
34131
17558
43847
38820
38644
17816
44636
3900
43524
1404
35344
39478
26052

For Feature 26600
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([3.6056e-08, 1.2117e-08, 7.7619e-09, 4.2814e-09, 2.4624e-09, 2.1998e-09,
        2.1889e-09, 2.0359e-09, 2.0342e-09, 1.8331e-09], device='cuda:0')
['carried' 'ohio' 'permanent' 'mouse' 'long' 'comfort' 'territory'
 'viewing' 'photo' 'using']

Most Change


Most Changed, by Absolute Diff Over 160 Images:
tensor([3.6056e-08, 1.2117e-08, 7.7619e-09, 4.2814e-09, 2.4624e-09, 2.1998e-09,
        2.1889e-09, 2.0359e-09, 2.0342e-09, 1.8331e-09], device='cuda:0')
['carried' 'ohio' 'permanent' 'mouse' 'long' 'comfort' 'territory'
 'viewing' 'photo' 'using']

Most Changed, by Ratio Over 160 Images:
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000], device='cuda:0')
['ohio' 'guides' 'let' 'plans' 'using' 'number' 'long' 'project' 'fully'
 'particularly']

For Feature 12950
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([3.6056e-08, 1.2117e-08, 7.7619e-09, 4.2814e-09, 2.4624e-09, 2.1998e-09,
        2.1889e-09, 2.0359e-09, 2.0342e-09, 1.8331e-09], device='cuda:0')
['carried' 'ohio' 'permanent' 'mouse' 'long' 'comfort' 'territory'
 'viewing' 'photo' 'using']

Most Changed, by Ratio Over 160 Images:
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1


Most Changed, by Absolute Diff Over 160 Images:
tensor([3.6056e-08, 1.2117e-08, 7.7619e-09, 4.2814e-09, 2.4624e-09, 2.1998e-09,
        2.1889e-09, 2.0359e-09, 2.0342e-09, 1.8331e-09], device='cuda:0')
['carried' 'ohio' 'permanent' 'mouse' 'long' 'comfort' 'territory'
 'viewing' 'photo' 'using']

Most Changed, by Ratio Over 160 Images:
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000], device='cuda:0')
['ohio' 'guides' 'let' 'plans' 'using' 'number' 'long' 'project' 'fully'
 'particularly']

For Feature 1366
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([3.6056e-08, 1.2117e-08, 7.7619e-09, 4.2814e-09, 2.4624e-09, 2.1998e-09,
        2.1889e-09, 2.0359e-09, 2.0342e-09, 1.8331e-09], device='cuda:0')
['carried' 'ohio' 'permanent' 'mouse' 'long' 'comfort' 'territory'
 'viewing' 'photo' 'using']

Most Changed, by Ratio Over 160 Images:
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.


Most Changed, by Absolute Diff Over 160 Images:
tensor([3.6056e-08, 1.2117e-08, 7.7619e-09, 4.2814e-09, 2.4624e-09, 2.1998e-09,
        2.1889e-09, 2.0359e-09, 2.0342e-09, 1.8331e-09], device='cuda:0')
['carried' 'ohio' 'permanent' 'mouse' 'long' 'comfort' 'territory'
 'viewing' 'photo' 'using']

Most Changed, by Ratio Over 160 Images:
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000], device='cuda:0')
['ohio' 'guides' 'let' 'plans' 'using' 'number' 'long' 'project' 'fully'
 'particularly']

For Feature 21158
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([3.6056e-08, 1.2117e-08, 7.7619e-09, 4.2814e-09, 2.4624e-09, 2.1998e-09,
        2.1889e-09, 2.0359e-09, 2.0342e-09, 1.8331e-09], device='cuda:0')
['carried' 'ohio' 'permanent' 'mouse' 'long' 'comfort' 'territory'
 'viewing' 'photo' 'using']

Most Changed, by Ratio Over 160 Images:
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1


Most Changed, by Absolute Diff Over 160 Images:
tensor([3.6056e-08, 1.2117e-08, 7.7619e-09, 4.2814e-09, 2.4624e-09, 2.1998e-09,
        2.1889e-09, 2.0359e-09, 2.0342e-09, 1.8331e-09], device='cuda:0')
['carried' 'ohio' 'permanent' 'mouse' 'long' 'comfort' 'territory'
 'viewing' 'photo' 'using']

Most Changed, by Ratio Over 160 Images:
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000], device='cuda:0')
['ohio' 'guides' 'let' 'plans' 'using' 'number' 'long' 'project' 'fully'
 'particularly']

For Feature 5823
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([3.6056e-08, 1.2117e-08, 7.7619e-09, 4.2814e-09, 2.4624e-09, 2.1998e-09,
        2.1889e-09, 2.0359e-09, 2.0342e-09, 1.8331e-09], device='cuda:0')
['carried' 'ohio' 'permanent' 'mouse' 'long' 'comfort' 'territory'
 'viewing' 'photo' 'using']

Most Changed, by Ratio Over 160 Images:
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.


Most Changed, by Absolute Diff Over 160 Images:
tensor([3.6056e-08, 1.2117e-08, 7.7619e-09, 4.2814e-09, 2.4624e-09, 2.1998e-09,
        2.1889e-09, 2.0359e-09, 2.0342e-09, 1.8331e-09], device='cuda:0')
['carried' 'ohio' 'permanent' 'mouse' 'long' 'comfort' 'territory'
 'viewing' 'photo' 'using']

Most Changed, by Ratio Over 160 Images:
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000], device='cuda:0')
['ohio' 'guides' 'let' 'plans' 'using' 'number' 'long' 'project' 'fully'
 'particularly']

For Feature 21597
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([3.6056e-08, 1.2117e-08, 7.7619e-09, 4.2814e-09, 2.4624e-09, 2.1998e-09,
        2.1889e-09, 2.0359e-09, 2.0342e-09, 1.8331e-09], device='cuda:0')
['carried' 'ohio' 'permanent' 'mouse' 'long' 'comfort' 'territory'
 'viewing' 'photo' 'using']

Most Changed, by Ratio Over 160 Images:
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1

['ohio' 'guides' 'let' 'plans' 'using' 'number' 'long' 'project' 'fully'
 'particularly']

For Feature 47779
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([3.6056e-08, 1.2117e-08, 7.7619e-09, 4.2814e-09, 2.4624e-09, 2.1998e-09,
        2.1889e-09, 2.0359e-09, 2.0342e-09, 1.8331e-09], device='cuda:0')
['carried' 'ohio' 'permanent' 'mouse' 'long' 'comfort' 'territory'
 'viewing' 'photo' 'using']

Most Changed, by Ratio Over 160 Images:
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000], device='cuda:0')
['ohio' 'guides' 'let' 'plans' 'using' 'number' 'long' 'project' 'fully'
 'particularly']

For Feature 44957
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([3.6056e-08, 1.2117e-08, 7.7619e-09, 4.2814e-09, 2.4624e-09, 2.1998e-09,
        2.1889e-09, 2.0359e-09, 2.0342e-09, 1.8331e-09], device='cuda:0')
['carried' 'ohio' 'permane

['birmingham' 'sand' 'mountain' 'disclosure' 'aug' 'atlanta' 'clay' 'rome'
 'bond' 'string']

For Feature 44636
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([3.6056e-08, 1.2117e-08, 7.7619e-09, 4.2814e-09, 2.4624e-09, 2.1998e-09,
        2.1889e-09, 2.0359e-09, 2.0342e-09, 1.8331e-09], device='cuda:0')
['carried' 'ohio' 'permanent' 'mouse' 'long' 'comfort' 'territory'
 'viewing' 'photo' 'using']

Most Changed, by Ratio Over 160 Images:
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000], device='cuda:0')
['ohio' 'guides' 'let' 'plans' 'using' 'number' 'long' 'project' 'fully'
 'particularly']

For Feature 3900
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([3.6056e-08, 1.2117e-08, 7.7619e-09, 4.2814e-09, 2.4624e-09, 2.1998e-09,
        2.1889e-09, 2.0359e-09, 2.0342e-09, 1.8331e-09], device='cuda:0')
['carried' 'ohio' 'perma

  0%|▎                                                                                                 | 4/1562 [00:30<3:18:42,  7.65s/it]


text_features_normed.shape: torch.Size([5000, 512])
26600
8518
16347
46981
44837
41588
46158
30052
36177
17551
35377
41389
12950
7623
48170
1527
22666
45420
36780
38339
22534
32663
2032
7697
23439
18977
1366
36950
44476
9108
42357
33482
2874
24884
17589
21462
561
5473
9246
7131
21158
13913
2705
21193
1807
48735
25174
13982
26171
4525
2722
31039
31221
9728
5823
253
24617
20914
30159
14840
3193
2490
39796
31782
33170
4333
26182
23970
21597
3031
15968
5767
45594
47466
34121
18305
7995
42826
19049
9407
3818
47779
44957
40803
41756
38695
38400
34131
17558
43847
38820
38644
17816
44636
3900
43524
1404
35344
39478
26052

For Feature 26600
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0093, 0.0047, 0.0034, 0.0033, 0.0031, 0.0028, 0.0028, 0.0026, 0.0024,
        0.0023], device='cuda:0')
['fucking' 'cute' 'pair' 'wet' 'playing' 'green' 'shaved' 'blonde'
 'copper' 'seller']

Most Changed, by Ratio Over 160 Images:
tensor([22.5281, 17

text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0051, 0.0030, 0.0020, 0.0019, 0.0015, 0.0014, 0.0012, 0.0011, 0.0009,
        0.0008], device='cuda:0')
['ray' 'foto' 'cute' 'male' 'foster' 'milfhunter' 'sri' 'kits' 'jerry'
 'milfs']

Most Changed, by Ratio Over 160 Images:
tensor([14.4122,  8.3170,  7.6503,  7.1491,  7.0684,  6.7371,  6.2476,  6.1082,
         5.7676,  5.7065], device='cuda:0')
['quotes' 'quote' 'tours' 'subsequent' 'forums' 'and' 'cruises' 'college'
 'download' 'wayne']

For Feature 7623
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0046, 0.0032, 0.0028, 0.0023, 0.0021, 0.0021, 0.0021, 0.0021, 0.0018,
        0.0017], device='cuda:0')
['vehicle' 'jr' 'cluster' 'stick' 'picture' 'dolls' 'roof' 'installed'
 'sharing' 'figure']

Most Changed, by Ratio Over 160 Images:
tensor([16.7930, 16.6172, 16.1967, 15.9033, 15.7438, 15.3105, 14.3771, 14.0104,
  


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0063, 0.0058, 0.0055, 0.0046, 0.0036, 0.0036, 0.0033, 0.0028, 0.0025,
        0.0025], device='cuda:0')
['yellow' 'turkey' 'guinea' 'conservation' 'fish' 'green' 'photo'
 'equipment' 'ireland' 'construction']

Most Changed, by Ratio Over 160 Images:
tensor([19.1581, 16.0720, 15.7927, 14.9024, 13.0402, 12.4827, 12.2196, 12.0767,
        11.4703, 10.8741], device='cuda:0')
['paint' 'nice' 'builder' 'tools' 'mining' 'pounds' 'supplies' 'czech'
 'equipment' 'lights']

For Feature 1366
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0065, 0.0049, 0.0031, 0.0029, 0.0026, 0.0025, 0.0024, 0.0022, 0.0020,
        0.0019], device='cuda:0')
['yellow' 'cluster' 'conservation' 'photo' 'buffalo' 'bird' 'model' 'foto'
 'purple' 'ken']

Most Changed, by Ratio Over 160 Images:
tensor([26.5528, 23.4327, 20.8123, 20.2959, 18.8028, 17.2976, 15.5066, 14.7373,
        14.2239, 14.0155], de


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0059, 0.0057, 0.0053, 0.0052, 0.0045, 0.0038, 0.0037, 0.0036, 0.0034,
        0.0033], device='cuda:0')
['epinions' 'hop' 'fish' 'python' 'spanking' 'pussy' 'bass' 'dragon'
 'yellow' 'golden']

Most Changed, by Ratio Over 160 Images:
tensor([21.8252, 14.3742, 13.3316, 13.3091, 11.6365, 10.1790,  9.3295,  9.3211,
         9.2760,  9.1521], device='cuda:0')
['mining' 'golf' 'fishing' 'hop' 'dildo' 'diamond' 'links' 'nurse' 'chips'
 'pizza']

For Feature 2705
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0157, 0.0095, 0.0067, 0.0029, 0.0023, 0.0023, 0.0021, 0.0020, 0.0020,
        0.0019], device='cuda:0')
['male' 'epinions' 'pair' 'african' 'beach' 'bug' 'dog' 'blue' 'mon'
 'recipe']

Most Changed, by Ratio Over 160 Images:
tensor([30.8225, 14.9319, 12.6757, 12.6702, 12.1641, 12.1430, 12.0261, 11.9804,
        11.7280, 11.6718], device='cuda:0')
['avatar' 'beach' 'tex


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0087, 0.0048, 0.0048, 0.0032, 0.0031, 0.0030, 0.0028, 0.0027, 0.0026,
        0.0024], device='cuda:0')
['ebony' 'fucking' 'labs' 'fish' 'pussy' 'looking' 'flying' 'eating'
 'roof' 'bugs']

Most Changed, by Ratio Over 160 Images:
tensor([39.1950, 23.8753, 18.3604, 13.2677, 12.0725, 11.2612, 10.6657, 10.2461,
        10.1063, 10.0156], device='cuda:0')
['jobs' 'black' 'ebony' 'shift' 'patterns' 'noise' 'knowing' 'thousands'
 'laptops' 'textbooks']

For Feature 20914
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0069, 0.0062, 0.0058, 0.0056, 0.0048, 0.0045, 0.0040, 0.0035, 0.0033,
        0.0027], device='cuda:0')
['bird' 'jacket' 'stick' 'dog' 'acrobat' 'leg' 'ray' 'legs' 'fish' 'tiny']

Most Changed, by Ratio Over 160 Images:
tensor([36.9416, 35.8112, 35.3903, 29.7859, 26.0103, 25.4081, 24.1861, 19.0751,
        18.2266, 16.7835], device='cuda:0')
['jacket' 'clothes


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0188, 0.0072, 0.0058, 0.0032, 0.0029, 0.0025, 0.0022, 0.0022, 0.0021,
        0.0019], device='cuda:0')
['stick' 'ray' 'cute' 'dodge' 'pump' 'male' 'jerry' 'bowl' 'cooling' 'leg']

Most Changed, by Ratio Over 160 Images:
tensor([20.6008, 19.6957, 18.4342, 17.4695, 14.9799, 12.0777, 11.4913, 11.0423,
        10.7145, 10.5795], device='cuda:0')
['dress' 'stick' 'ross' 'hat' 'snow' 'thermal' 'ice' 'winter' 'felt'
 'bruce']

For Feature 47466
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0090, 0.0064, 0.0038, 0.0034, 0.0034, 0.0032, 0.0031, 0.0030, 0.0030,
        0.0024], device='cuda:0')
['playing' 'fucking' 'eating' 'installation' 'epinions' 'pussy' 'table'
 'photo' 'milfhunter' 'set']

Most Changed, by Ratio Over 160 Images:
tensor([34.9989, 22.0403, 20.9499, 16.9034, 15.6041, 15.3934, 15.3227, 14.3256,
        13.6634, 13.4409], device='cuda:0')
['vancouver' 'plate


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0108, 0.0054, 0.0040, 0.0037, 0.0036, 0.0033, 0.0030, 0.0029, 0.0028,
        0.0025], device='cuda:0')
['pair' 'permit' 'wildlife' 'pump' 'hairy' 'yellow' 'photo' 'lab' 'stick'
 'blue']

Most Changed, by Ratio Over 160 Images:
tensor([22.3121, 18.5602, 17.0442, 16.8839, 16.1448, 15.1099, 14.6108, 14.0304,
        14.0122, 13.6965], device='cuda:0')
['stable' 'purple' 'clinic' 'public' 'group' 'textbooks' 'accessible'
 'blue' 'printer' 'rehabilitation']

For Feature 17558
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0053, 0.0051, 0.0049, 0.0046, 0.0046, 0.0040, 0.0029, 0.0028, 0.0026,
        0.0026], device='cuda:0')
['flying' 'shaved' 'conservation' 'detail' 'seal' 'wildlife' 'jr'
 'packaging' 'dakota' 'riding']

Most Changed, by Ratio Over 160 Images:
tensor([13.8958, 11.5527, 10.7063, 10.5977, 10.4024, 10.1083, 10.0875, 10.0085,
        10.0049,  9.7257], devic

  0%|▎                                                                                                 | 4/1562 [00:31<3:27:39,  8.00s/it]


text_features_normed.shape: torch.Size([5000, 512])
26600
8518
16347
46981
44837
41588
46158
30052
36177
17551
35377
41389
12950
7623
48170
1527
22666
45420
36780
38339
22534
32663
2032
7697
23439
18977
1366
36950
44476
9108
42357
33482
2874
24884
17589
21462
561
5473
9246
7131
21158
13913
2705
21193
1807
48735
25174
13982
26171
4525
2722
31039
31221
9728
5823
253
24617
20914
30159
14840
3193
2490
39796
31782
33170
4333
26182
23970
21597
3031
15968
5767
45594
47466
34121
18305
7995
42826
19049
9407
3818
47779
44957
40803
41756
38695
38400
34131
17558
43847
38820
38644
17816
44636
3900
43524
1404
35344
39478
26052

For Feature 26600
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0106, 0.0104, 0.0085, 0.0077, 0.0058, 0.0047, 0.0046, 0.0045, 0.0040,
        0.0038], device='cuda:0')
['fucking' 'wet' 'cute' 'suck' 'copper' 'green' 'opened' 'blonde' 'shaved'
 'fell']

Most Changed, by Ratio Over 160 Images:
tensor([379.4778, 287.


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0090, 0.0084, 0.0066, 0.0064, 0.0055, 0.0055, 0.0052, 0.0051, 0.0051,
        0.0046], device='cuda:0')
['reproduction' 'yellow' 'cell' 'thumbnail' 'chip' 'preparation'
 'cooperation' 'fighting' 'scottish' 'playing']

Most Changed, by Ratio Over 160 Images:
tensor([402.4462, 336.5528, 322.6241, 282.1772, 233.3263, 222.8878, 220.5719,
        208.0146, 190.4294, 188.1410], device='cuda:0')
['professional' 'occupation' 'professionals' 'prison' 'cooperation'
 'prince' 'jordan' 'contractor' 'phentermine' 'contractors']

For Feature 12950
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0066, 0.0051, 0.0033, 0.0025, 0.0022, 0.0021, 0.0019, 0.0018, 0.0018,
        0.0018], device='cuda:0')
['ray' 'foto' 'cute' 'sri' 'images' 'male' 'milfs' 'jerry' 'charles'
 'shown']

Most Changed, by Ratio Over 160 Images:
tensor([354.5569, 111.1787,  76.2714,  65.1415,  63.4381,  62.8890, 


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0087, 0.0070, 0.0065, 0.0064, 0.0063, 0.0062, 0.0061, 0.0054, 0.0052,
        0.0044], device='cuda:0')
['kits' 'bowl' 'sole' 'balls' 'commission' 'lighting' 'ray' 'golden'
 'winning' 'ball']

Most Changed, by Ratio Over 160 Images:
tensor([1298.0518,  494.4666,  403.0589,  375.6049,  298.1186,  192.4739,
         165.3473,  161.3521,  147.2440,  139.1078], device='cuda:0')
['lighting' 'eyes' 'winning' 'led' 'lights' 'commission' 'lamp' 'away'
 'ea' 'specs']

For Feature 23439
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0109, 0.0100, 0.0087, 0.0085, 0.0080, 0.0078, 0.0067, 0.0060, 0.0052,
        0.0047], device='cuda:0')
['sole' 'bowl' 'dish' 'fish' 'gnu' 'boat' 'installed' 'hunting' 'cooling'
 'box']

Most Changed, by Ratio Over 160 Images:
tensor([564.5954, 308.1537, 196.9461, 181.1664, 171.4075, 127.9319, 126.5646,
        117.4936, 116.9091, 116.4122], device

tensor([1523.3300,  757.9642,  608.4072,  594.2497,  492.9212,  490.1532,
         475.0215,  400.9212,  345.3046,  309.1868], device='cuda:0')
['trucks' 'trailers' 'edward' 'header' 'horses' 'warehouse' 'catering'
 'bedroom' 'truck' 'banner']

For Feature 561
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0062, 0.0055, 0.0054, 0.0050, 0.0049, 0.0038, 0.0038, 0.0034, 0.0033,
        0.0033], device='cuda:0')
['console' 'epinions' 'pan' 'baker' 'african' 'bass' 'sub' 'eating' 'hop'
 'milf']

Most Changed, by Ratio Over 160 Images:
tensor([128.5919, 100.9431,  76.9961,  74.0695,  65.5886,  63.8463,  62.8418,
         62.7346,  61.9385,  58.3608], device='cuda:0')
['breakfast' 'baker' 'pain' 'protein' 'half' 'kitchen' 'console'
 'creation' 'lake' 'raw']

For Feature 5473
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0111, 0.0083, 0.0071, 0.0071, 0.0069, 0.0065, 0.00


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0127, 0.0103, 0.0102, 0.0087, 0.0070, 0.0064, 0.0058, 0.0057, 0.0056,
        0.0040], device='cuda:0')
['playing' 'flying' 'hairy' 'white' 'blowjob' 'baby' 'turned' 'foster'
 'after' 'visitor']

Most Changed, by Ratio Over 160 Images:
tensor([239.2974, 197.2539, 188.9561, 171.1585, 162.1608, 143.0183, 137.6050,
        129.1196, 111.8008,  95.3965], device='cuda:0')
['white' 'wheels' 'rush' 'thing' 'floor' 'concrete' 'afghanistan'
 'lesbian' 'philosophy' 'parents']

For Feature 5823
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0263, 0.0256, 0.0233, 0.0106, 0.0077, 0.0075, 0.0075, 0.0066, 0.0062,
        0.0058], device='cuda:0')
['laser' 'pair' 'pussy' 'douglas' 'opened' 'benefit' 'female' 'pioneer'
 'chamber' 'polish']

Most Changed, by Ratio Over 160 Images:
tensor([1045.7361,  544.8329,  377.4377,  302.9567,  282.1878,  204.7370,
         204.2649,  198.1161,  


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0060, 0.0043, 0.0039, 0.0038, 0.0038, 0.0035, 0.0033, 0.0031, 0.0031,
        0.0030], device='cuda:0')
['basket' 'cock' 'installation' 'package' 'elizabeth' 'install' 'plastic'
 'wire' 'mac' 'tiny']

Most Changed, by Ratio Over 160 Images:
tensor([640.5016, 488.7363, 358.1396, 302.2025, 296.8300, 289.9045, 249.1719,
        229.4557, 226.1790, 215.7825], device='cuda:0')
['kitchen' 'basket' 'factory' 'garage' 'bags' 'bedroom' 'dvds' 'workshop'
 'elizabeth' 'package']

For Feature 26182
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0193, 0.0166, 0.0075, 0.0065, 0.0061, 0.0058, 0.0058, 0.0056, 0.0055,
        0.0049], device='cuda:0')
['fish' 'photo' 'pussy' 'dog' 'bugs' 'huge' 'legs' 'fucking' 'neck'
 'finished']

Most Changed, by Ratio Over 160 Images:
tensor([382.7297, 289.5185, 272.2830, 187.1649, 161.5492, 161.2749, 160.1175,
        147.2097, 127.6389, 109.7062


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0257, 0.0114, 0.0080, 0.0065, 0.0052, 0.0052, 0.0050, 0.0050, 0.0048,
        0.0046], device='cuda:0')
['photo' 'pair' 'foto' 'sitting' 'hunting' 'detail' 'golden' 'bush'
 'installed' 'named']

Most Changed, by Ratio Over 160 Images:
tensor([400.6685, 214.9686, 173.6959, 167.9903, 161.9457, 147.9566, 108.0536,
         98.0218,  96.8698,  95.5664], device='cuda:0')
['putting' 'nashville' 'button' 'alabama' 'office' 'clock' 'leather'
 'rhode' 'marshall' 'named']

For Feature 41756
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0096, 0.0094, 0.0094, 0.0090, 0.0083, 0.0073, 0.0054, 0.0054, 0.0048,
        0.0047], device='cuda:0')
['epinions' 'acrobat' 'seal' 'figure' 'sequence' 'pussy' 'auction' 'hairy'
 'permit' 'turkey']

Most Changed, by Ratio Over 160 Images:
tensor([370.6787, 303.0593, 206.3346, 201.0964, 173.8396, 172.0887, 166.0388,
        157.1353, 140.8177, 


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0145, 0.0126, 0.0105, 0.0095, 0.0087, 0.0066, 0.0062, 0.0052, 0.0049,
        0.0048], device='cuda:0')
['stick' 'profile' 'inspection' 'rear' 'glance' 'photo' 'my' 'hairy'
 'board' 'pregnant']

Most Changed, by Ratio Over 160 Images:
tensor([206.3621, 192.4244, 171.8450, 169.6880, 167.4861, 149.1917, 144.8879,
        141.7597, 125.9508, 119.8023], device='cuda:0')
['directory' 'editing' 'profile' 'gallery' 'door' 'posters' 'tie' 'panel'
 'college' 'guestbook']

For Feature 1404
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0100, 0.0064, 0.0062, 0.0046, 0.0035, 0.0032, 0.0031, 0.0026, 0.0025,
        0.0024], device='cuda:0')
['yellow' 'turkey' 'pink' 'orange' 'indian' 'dogs' 'golden' 'epinions'
 'thermal' 'gnu']

Most Changed, by Ratio Over 160 Images:
tensor([608.9018, 292.6440, 202.7758, 199.2206, 180.9242, 180.8877, 178.4068,
        170.2256, 164.4755, 158.310

  0%|▎                                                                                                 | 4/1562 [00:31<3:22:28,  7.80s/it]


text_features_normed.shape: torch.Size([5000, 512])
26600
8518
16347
46981
44837
41588
46158
30052
36177
17551
35377
41389
12950
7623
48170
1527
22666
45420
36780
38339
22534
32663
2032
7697
23439
18977
1366
36950
44476
9108
42357
33482
2874
24884
17589
21462
561
5473
9246
7131
21158
13913
2705
21193
1807
48735
25174
13982
26171
4525
2722
31039
31221
9728
5823
253
24617
20914
30159
14840
3193
2490
39796
31782
33170
4333
26182
23970
21597
3031
15968
5767
45594
47466
34121
18305
7995
42826
19049
9407
3818
47779
44957
40803
41756
38695
38400
34131
17558
43847
38820
38644
17816
44636
3900
43524
1404
35344
39478
26052

For Feature 26600
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0225, 0.0198, 0.0156, 0.0150, 0.0106, 0.0106, 0.0098, 0.0091, 0.0091,
        0.0087], device='cuda:0')
['al' 'wet' 'suck' 'it' 'k' 'copper' 'silver' 'ky' 'named' 'fell']

Most Changed, by Ratio Over 160 Images:
tensor([9193.6299, 9129.9258, 3917.0981


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0310, 0.0216, 0.0186, 0.0157, 0.0130, 0.0119, 0.0107, 0.0100, 0.0094,
        0.0077], device='cuda:0')
['thumbnail' 'jordan' 'reproduction' 'cooperation' 'scottish'
 'professional' 'chip' 'preparation' 'spanish' 'iraqi']

Most Changed, by Ratio Over 160 Images:
tensor([11123.4600,  8190.7158,  7147.4268,  6548.8198,  6482.5791,  6307.0029,
         5828.1055,  5118.6694,  4927.0947,  4677.1963], device='cuda:0')
['professional' 'professionals' 'occupation' 'cooperation' 'contractors'
 'prison' 'phentermine' 'contractor' 'builder' 'apartments']

For Feature 12950
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0045, 0.0044, 0.0041, 0.0039, 0.0039, 0.0037, 0.0036, 0.0031, 0.0030,
        0.0029], device='cuda:0')
['shown' 'images' 'foto' 'and' 'tours' 'john' 'sri' 'milfs' 'for'
 'charles']

Most Changed, by Ratio Over 160 Images:
tensor([31887.1621,  4087.2205,  1969.9


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0654, 0.0323, 0.0245, 0.0192, 0.0146, 0.0127, 0.0122, 0.0101, 0.0085,
        0.0079], device='cuda:0')
['lighting' 'winning' 'commission' 'eyes' 'balls' 'specs' 'gcc' 'led'
 'permalink' 'kits']

Most Changed, by Ratio Over 160 Images:
tensor([100185.9141,  19118.7910,  16828.3789,  11708.3545,  10779.5459,
          4391.3564,   4281.8384,   3659.2793,   3657.2231,   3546.4055],
       device='cuda:0')
['lighting' 'eyes' 'led' 'lights' 'winning' 'lamp' 'bags' 'doors' 'quotes'
 'ea']

For Feature 23439
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0327, 0.0261, 0.0226, 0.0171, 0.0131, 0.0119, 0.0105, 0.0103, 0.0095,
        0.0089], device='cuda:0')
['boat' 'bowl' 'dish' 'front' 'gnu' 'sole' 'belt' 'installed' 'diff'
 'meat']

Most Changed, by Ratio Over 160 Images:
tensor([34373.0078, 14146.4785,  7609.6987,  7214.3657,  5565.6382,  5205.6572,
         3666.2642,  


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0351, 0.0255, 0.0179, 0.0177, 0.0161, 0.0161, 0.0146, 0.0134, 0.0132,
        0.0083], device='cuda:0')
['edward' 'trucks' 'fox' 'kerry' 'wings' 'rolling' 'dogs' 'trailers'
 'site' 'wallpapers']

Most Changed, by Ratio Over 160 Images:
tensor([104068.6562,  35452.0938,  25136.7676,  22070.6582,  21593.9297,
         17751.8262,  16856.5020,  16691.0352,  11174.5381,  10960.3604],
       device='cuda:0')
['trucks' 'trailers' 'header' 'catering' 'bedroom' 'horses' 'warehouse'
 'edward' 'kitchen' 'wallpapers']

For Feature 561
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0144, 0.0116, 0.0106, 0.0085, 0.0082, 0.0078, 0.0074, 0.0073, 0.0071,
        0.0064], device='cuda:0')
['pan' 'console' 'half' 'sterling' 'baker' 'tall' 'raw' 'sw' 'feeds'
 'virgin']

Most Changed, by Ratio Over 160 Images:
tensor([4827.6611, 2230.4329, 2062.8987, 1647.6523, 1572.7568, 1466.2328,
   


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0338, 0.0187, 0.0175, 0.0167, 0.0150, 0.0116, 0.0106, 0.0104, 0.0095,
        0.0081], device='cuda:0')
['shemale' 'michael' 'jordan' 'swiss' 'sterling' 'iran' 'roberts' 'phil'
 'smaller' 'southern']

Most Changed, by Ratio Over 160 Images:
tensor([6637.6890, 5530.6851, 3855.9431, 2699.5916, 2381.9846, 2125.0852,
        1649.8616, 1543.0645, 1345.3627, 1342.9926], device='cuda:0')
['iran' 'tennessee' 'michael' 'physics' 'jordan' 'switzerland' 'caribbean'
 'georgia' 'ky' 'oregon']

For Feature 26171
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0337, 0.0173, 0.0100, 0.0097, 0.0095, 0.0078, 0.0074, 0.0071, 0.0069,
        0.0065], device='cuda:0')
['pull' 'compact' 'jersey' 'converted' 'receiving' 'upper' 'atlantic'
 'modified' 'epinions' 'mon']

Most Changed, by Ratio Over 160 Images:
tensor([3743.4712, 3496.5212, 3227.5879, 2352.4141, 2206.3855, 2044.2961,
        


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0326, 0.0261, 0.0234, 0.0217, 0.0142, 0.0141, 0.0117, 0.0085, 0.0085,
        0.0056], device='cuda:0')
['hop' 'thai' 'pakistan' 'sri' 'simpson' 'interracial' 'african' 'link'
 's' 'chicken']

Most Changed, by Ratio Over 160 Images:
tensor([13142.2031, 12660.7998,  7346.2983,  6515.7495,  4533.5835,  4458.0557,
         4007.2695,  3957.5710,  3851.7656,  3053.9390], device='cuda:0')
['pakistan' 'sitemap' 'simpson' 'interracial' 'phentermine' 'employer'
 'downloads' 'download' 'affiliates' 'hop']

For Feature 3193
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0632, 0.0139, 0.0133, 0.0109, 0.0090, 0.0083, 0.0081, 0.0075, 0.0075,
        0.0075], device='cuda:0')
['li' 'standing' 'border' 'l' 'font' 'weight' 'muscle' 'button' 'brown'
 'cd']

Most Changed, by Ratio Over 160 Images:
tensor([3113.1785, 3043.3777, 2526.8315, 2184.9299, 2152.8225, 2125.0376,
        2081.8


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0810, 0.0732, 0.0406, 0.0236, 0.0223, 0.0159, 0.0157, 0.0142, 0.0117,
        0.0102], device='cuda:0')
['photo' 'my' 'after' 'brown' 'before' 'chocolate' 'thumbnail' 'foto'
 'shown' 'picture']

Most Changed, by Ratio Over 160 Images:
tensor([20406.3535,  5637.1230,  5391.0796,  3776.7441,  2873.4060,  2509.9941,
         2307.5737,  1942.4799,  1854.4883,  1850.2787], device='cuda:0')
['chocolate' 'my' 'lamp' 'plant' 'after' 'customer' 'plants' 'led'
 'customize' 'before']

For Feature 45594
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.1502, 0.0167, 0.0164, 0.0122, 0.0119, 0.0107, 0.0100, 0.0085, 0.0075,
        0.0067], device='cuda:0')
['stick' 'thermal' 'ross' 'font' 'cute' 'hat' 'bruce' 'felt' 'dodge'
 'jerry']

Most Changed, by Ratio Over 160 Images:
tensor([24299.0625, 10303.6670,  7692.4487,  5764.7651,  5729.0889,  3986.5964,
         2156.6052,  2143.2234


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0480, 0.0240, 0.0233, 0.0131, 0.0120, 0.0116, 0.0108, 0.0096, 0.0092,
        0.0080], device='cuda:0')
['photo' 'named' 'button' 'shown' 'pin' 'marshall' 'bush' 'si' 'rhode'
 'alabama']

Most Changed, by Ratio Over 160 Images:
tensor([13372.9268, 10442.4082,  4578.7729,  4521.0801,  4305.6655,  3293.3469,
         2515.4109,  2365.6743,  2361.0718,  1929.4258], device='cuda:0')
['putting' 'nashville' 'office' 'alabama' 'button' 'clock' 'boston'
 'rhode' 'leather' 'citysearch']

For Feature 41756
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0298, 0.0148, 0.0142, 0.0130, 0.0111, 0.0111, 0.0110, 0.0101, 0.0099,
        0.0092], device='cuda:0')
['figure' 'auction' 'board' 'sequence' 'epson' 'sign' 'deck'
 'advertisement' 'card' 'seal']

Most Changed, by Ratio Over 160 Images:
tensor([22633.3867, 12259.2529, 10144.2588,  6705.3735,  5099.9937,  5056.0537,
         477


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0386, 0.0230, 0.0183, 0.0153, 0.0151, 0.0132, 0.0100, 0.0097, 0.0091,
        0.0084], device='cuda:0')
['profile' 'inspection' 'panel' 'rear' 'board' 'stick' 'pregnant' 'glance'
 'my' 'checking']

Most Changed, by Ratio Over 160 Images:
tensor([6361.4785, 6188.1787, 5245.0610, 5024.5986, 4668.9175, 4327.7007,
        4180.5210, 3652.2703, 3356.3677, 3213.6282], device='cuda:0')
['directory' 'posters' 'editing' 'door' 'gallery' 'college' 'tie'
 'profile' 'aluminum' 'panel']

For Feature 1404
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0132, 0.0115, 0.0085, 0.0072, 0.0067, 0.0051, 0.0050, 0.0048, 0.0040,
        0.0039], device='cuda:0')
['pink' 'orange' 'yellow' 'indian' 'ukraine' 'thermal' 'russian' 'turkey'
 'password' 'inch']

Most Changed, by Ratio Over 160 Images:
tensor([34198.9844, 12382.2939,  5324.3608,  4833.1118,  4777.4253,  4697.5718,
         4552.74

  0%|▎                                                                                                 | 4/1562 [00:31<3:26:19,  7.95s/it]


text_features_normed.shape: torch.Size([5000, 512])
26600
8518
16347
46981
44837
41588
46158
30052
36177
17551
35377
41389
12950
7623
48170
1527
22666
45420
36780
38339
22534
32663
2032
7697
23439
18977
1366
36950
44476
9108
42357
33482
2874
24884
17589
21462
561
5473
9246
7131
21158
13913
2705
21193
1807
48735
25174
13982
26171
4525
2722
31039
31221
9728
5823
253
24617
20914
30159
14840
3193
2490
39796
31782
33170
4333
26182
23970
21597
3031
15968
5767
45594
47466
34121
18305
7995
42826
19049
9407
3818
47779
44957
40803
41756
38695
38400
34131
17558
43847
38820
38644
17816
44636
3900
43524
1404
35344
39478
26052

For Feature 26600
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0636, 0.0336, 0.0204, 0.0183, 0.0182, 0.0167, 0.0163, 0.0151, 0.0125,
        0.0114], device='cuda:0')
['al' 'it' 'named' 'k' 'ky' 'silver' 'or' 'h' 'wet' 'suck']

Most Changed, by Ratio Over 160 Images:
tensor([163590.6562, 107465.3516,  77284.6172,


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0916, 0.0468, 0.0398, 0.0192, 0.0162, 0.0157, 0.0156, 0.0137, 0.0133,
        0.0101], device='cuda:0')
['thumbnail' 'professional' 'jordan' 'professionals' 'cooperation'
 'spanish' 'reproduction' 'greek' 'scottish' 'occupation']

Most Changed, by Ratio Over 160 Images:
tensor([135509.2031, 107638.6250, 102685.9453,  93720.4141,  86579.5859,
         71696.8984,  70772.7969,  70697.6719,  66465.1875,  65293.9648],
       device='cuda:0')
['contractors' 'professional' 'apartments' 'cooperation' 'scotland'
 'prison' 'phentermine' 'apartment' 'occupation' 'professionals']

For Feature 12950
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0150, 0.0073, 0.0072, 0.0059, 0.0059, 0.0046, 0.0045, 0.0045, 0.0041,
        0.0041], device='cuda:0')
['and' 'oh' 'for' 'shown' 'tours' 'other' 'quotes' 'john' 'wayne' 'images']

Most Changed, by Ratio Over 160 Images:
tensor([1660876.


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.3027, 0.0510, 0.0316, 0.0279, 0.0253, 0.0140, 0.0132, 0.0117, 0.0104,
        0.0090], device='cuda:0')
['lighting' 'winning' 'led' 'eyes' 'commission' 'specs' 'gcc' 'balls'
 'permalink' 'championship']

Most Changed, by Ratio Over 160 Images:
tensor([2363312.7500,  291245.5938,  231178.4062,  191839.7812,   96986.4531,
          90549.4766,   66570.5859,   60374.3438,   46706.5117,   43862.4727],
       device='cuda:0')
['lighting' 'led' 'eyes' 'lights' 'quotes' 'winning' 'lamp' 'bags' 'trees'
 'arrival']

For Feature 23439
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0960, 0.0763, 0.0587, 0.0320, 0.0296, 0.0193, 0.0163, 0.0119, 0.0117,
        0.0109], device='cuda:0')
['boat' 'bowl' 'front' 'dish' 'belt' 'filters' 'meat' 'theater' 'trailer'
 'tool']

Most Changed, by Ratio Over 160 Images:
tensor([1062878.1250,  616265.8125,  154865.6719,  134103.1719,  130806.4


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0839, 0.0627, 0.0444, 0.0386, 0.0285, 0.0202, 0.0198, 0.0154, 0.0146,
        0.0131], device='cuda:0')
['trucks' 'edward' 'trailers' 'header' 'site' 'wallpapers' 'video'
 'banner' 'truck' 'fox']

Most Changed, by Ratio Over 160 Images:
tensor([2171038.0000,  815585.0625,  496949.5625,  389081.5938,  378508.2188,
         234962.9844,  231249.3594,  227660.6094,  226579.4531,  199013.7344],
       device='cuda:0')
['trucks' 'bedroom' 'trailers' 'catering' 'header' 'horses' 'wallpapers'
 'quotes' 'warehouse' 'kitchen']

For Feature 561
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0187, 0.0179, 0.0144, 0.0119, 0.0116, 0.0112, 0.0105, 0.0086, 0.0085,
        0.0083], device='cuda:0')
['half' 'pan' 'sterling' 'virgin' 'raw' 'console' 'tall' 'baker' 'feeds'
 'sw']

Most Changed, by Ratio Over 160 Images:
tensor([122540.2031,  73319.5859,  50141.5547,  48489.3555,  32521


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0374, 0.0361, 0.0315, 0.0274, 0.0239, 0.0186, 0.0160, 0.0140, 0.0130,
        0.0125], device='cuda:0')
['jordan' 'shemale' 'michael' 'sterling' 'swiss' 'roberts' 'iran' 'phil'
 'southern' 'k']

Most Changed, by Ratio Over 160 Images:
tensor([211347.6562, 118668.4297,  69992.0469,  48380.0156,  46943.0469,
         45972.7773,  45576.0625,  42145.6562,  41076.9648,  38702.4336],
       device='cuda:0')
['tennessee' 'iran' 'switzerland' 'ireland' 'alabama' 'arkansas'
 'nebraska' 'pakistan' 'michael' 'delaware']

For Feature 26171
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0693, 0.0397, 0.0179, 0.0163, 0.0149, 0.0125, 0.0114, 0.0109, 0.0103,
        0.0098], device='cuda:0')
['pull' 'compact' 'receiving' 'jersey' 'buttons' 'irish' 'external'
 'upper' 'aircraft' 'converted']

Most Changed, by Ratio Over 160 Images:
tensor([138454.0781,  53145.5273,  51524.2930,  433


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0381, 0.0339, 0.0296, 0.0260, 0.0227, 0.0141, 0.0135, 0.0118, 0.0099,
        0.0094], device='cuda:0')
['pakistan' 'simpson' 'thai' 'hop' 'sri' 'interracial' 'sitemap' 'link'
 's' 'google']

Most Changed, by Ratio Over 160 Images:
tensor([656556.0625, 281779.4688, 228404.0000, 143281.8281, 106638.9766,
         92617.8984,  85626.3047,  81241.0078,  78465.1406,  67407.2578],
       device='cuda:0')
['pakistan' 'sitemap' 'simpson' 'interracial' 'phentermine' 'download'
 'thing' 'employer' 'affiliates' 'tripadvisor']

For Feature 3193
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.1183, 0.0194, 0.0176, 0.0166, 0.0156, 0.0141, 0.0138, 0.0137, 0.0129,
        0.0122], device='cuda:0')
['li' 'l' 'button' 'cd' 'dvd' 'h' 'font' 'y' 'weight' 'u']

Most Changed, by Ratio Over 160 Images:
tensor([55705.9258, 54197.1133, 50624.4688, 29936.1074, 27849.1406, 27039.7031,
        


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0975, 0.0768, 0.0538, 0.0488, 0.0474, 0.0229, 0.0202, 0.0200, 0.0162,
        0.0119], device='cuda:0')
['my' 'photo' 'after' 'thumbnail' 'chocolate' 'before' 'brown' 'shown'
 'product' 'lamp']

Most Changed, by Ratio Over 160 Images:
tensor([395099.8438, 120407.2656,  55072.0312,  47878.6133,  44544.2383,
         43666.4023,  31488.5977,  30389.8945,  27510.6758,  24221.6953],
       device='cuda:0')
['chocolate' 'lamp' 'customer' 'plant' 'my' 'plants' 'crafts' 'led'
 'mountains' 'packaging']

For Feature 45594
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.2002, 0.0400, 0.0312, 0.0196, 0.0189, 0.0130, 0.0121, 0.0112, 0.0111,
        0.0103], device='cuda:0')
['stick' 'hat' 'ross' 'thermal' 'font' 'felt' 'bruce' 'columbia' 'y'
 'pick']

Most Changed, by Ratio Over 160 Images:
tensor([715277.5625, 450865.5938, 236692.7344,  86004.5547,  81209.8047,
         65010.41


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0867, 0.0668, 0.0358, 0.0226, 0.0222, 0.0219, 0.0205, 0.0191, 0.0157,
        0.0143], device='cuda:0')
['button' 'named' 'photo' 'marshall' 'pin' 'front' 'shown' 'si' 'alabama'
 'type']

Most Changed, by Ratio Over 160 Images:
tensor([539672.6250, 268924.0312, 209041.8750,  78524.5078,  61430.3242,
         57217.9570,  52233.1758,  49131.3242,  48438.3125,  43950.2734],
       device='cuda:0')
['nashville' 'alabama' 'putting' 'office' 'pittsburgh' 'button' 'virginia'
 'rhode' 'bedroom' 'boston']

For Feature 41756
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0475, 0.0469, 0.0447, 0.0435, 0.0383, 0.0200, 0.0177, 0.0177, 0.0157,
        0.0149], device='cuda:0')
['sign' 'advertisement' 'figure' 'card' 'certificates' 'board' 'epson'
 'deck' 'auction' 'deal']

Most Changed, by Ratio Over 160 Images:
tensor([726331.3750, 266927.8438, 235279.9062, 111736.2500, 110633.6


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0477, 0.0387, 0.0262, 0.0192, 0.0174, 0.0145, 0.0131, 0.0098, 0.0098,
        0.0093], device='cuda:0')
['profile' 'panel' 'board' 'inspection' 'door' 'directory' 'rear' 'tabs'
 'sign' 'bookmark']

Most Changed, by Ratio Over 160 Images:
tensor([227353.6250, 172114.5781, 118748.2266, 112413.0000,  72176.1797,
         71083.6719,  61930.9258,  58871.9648,  55657.5273,  53058.7148],
       device='cuda:0')
['posters' 'editing' 'college' 'directory' 'door' 'gallery' 'dress' 'tie'
 'guestbook' 'aluminum']

For Feature 1404
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0233, 0.0202, 0.0144, 0.0097, 0.0086, 0.0085, 0.0066, 0.0064, 0.0064,
        0.0059], device='cuda:0')
['pink' 'orange' 'coins' 'reviewed' 'countries' 'ukraine' 'password'
 'russian' 'generic' 'indian']

Most Changed, by Ratio Over 160 Images:
tensor([855403.9375, 301912.8125, 124747.1797, 124144.7656, 1

  0%|▎                                                                                                 | 4/1562 [00:31<3:27:14,  7.98s/it]


text_features_normed.shape: torch.Size([5000, 512])
26600
8518
16347
46981
44837
41588
46158
30052
36177
17551
35377
41389
12950
7623
48170
1527
22666
45420
36780
38339
22534
32663
2032
7697
23439
18977
1366
36950
44476
9108
42357
33482
2874
24884
17589
21462
561
5473
9246
7131
21158
13913
2705
21193
1807
48735
25174
13982
26171
4525
2722
31039
31221
9728
5823
253
24617
20914
30159
14840
3193
2490
39796
31782
33170
4333
26182
23970
21597
3031
15968
5767
45594
47466
34121
18305
7995
42826
19049
9407
3818
47779
44957
40803
41756
38695
38400
34131
17558
43847
38820
38644
17816
44636
3900
43524
1404
35344
39478
26052

For Feature 26600
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0816, 0.0380, 0.0256, 0.0200, 0.0192, 0.0182, 0.0180, 0.0179, 0.0137,
        0.0110], device='cuda:0')
['al' 'it' 'named' 'ky' 'silver' 'k' 'or' 'h' 'tn' 'j']

Most Changed, by Ratio Over 160 Images:
tensor([697771.9375, 356784.5312, 289881.5000, 111


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0315, 0.0224, 0.0222, 0.0181, 0.0165, 0.0162, 0.0154, 0.0128, 0.0122,
        0.0116], device='cuda:0')
['ink' 'plates' 'sole' 'breast' 'hat' 'flags' 'breasts' 'thumbnail'
 'notebook' 'wings']

Most Changed, by Ratio Over 160 Images:
tensor([831759.1875, 763929.5625, 605551.6875, 567060.9375, 331367.3750,
        269969.7188, 252499.1250, 244702.4219, 239483.0312, 204130.7500],
       device='cuda:0')
['roses' 'plants' 'boats' 'hat' 'flags' 'notebooks' 'recipes' 'pink'
 'fans' 'purple']

For Feature 41389
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.1291, 0.0656, 0.0377, 0.0260, 0.0163, 0.0150, 0.0117, 0.0111, 0.0106,
        0.0094], device='cuda:0')
['thumbnail' 'professional' 'jordan' 'professionals' 'spanish' 'greek'
 'cooperation' 'reproduction' 'scottish' 'occupation']

Most Changed, by Ratio Over 160 Images:
tensor([534037.0625, 522630.8125, 446029.0000, 413


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0461, 0.0457, 0.0364, 0.0229, 0.0221, 0.0218, 0.0218, 0.0211, 0.0160,
        0.0150], device='cuda:0')
['led' 'phones' 'casinos' 'betting' 'yellow' 'matches' 'counties' 'purple'
 'holdem' 'shoes']

Most Changed, by Ratio Over 160 Images:
tensor([5296786.0000, 3174117.2500, 1526074.8750, 1313385.6250, 1177128.8750,
        1006002.9375,  989473.1250,  979579.3125,  876845.1875,  857849.0000],
       device='cuda:0')
['casinos' 'counties' 'trees' 'phones' 'colleges' 'buildings' 'betting'
 'bedroom' 'purple' 'mountains']

For Feature 36950
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.1729, 0.0416, 0.0350, 0.0296, 0.0158, 0.0118, 0.0104, 0.0077, 0.0076,
        0.0074], device='cuda:0')
['mac' 'ba' 'purple' 'queen' 'white' 'files' 'front' 'graphic' 'ha'
 'relief']

Most Changed, by Ratio Over 160 Images:
tensor([1593424.2500, 1292146.6250,  199067.8281,  196774.8281, 


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.3141, 0.1773, 0.1401, 0.0575, 0.0141, 0.0072, 0.0070, 0.0056, 0.0051,
        0.0049], device='cuda:0')
['stands' 'stand' 'portable' 'holder' 'walker' 'crafts' 'chair' 'holds'
 'helping' 'furniture']

Most Changed, by Ratio Over 160 Images:
tensor([1239880.5000,  851999.6875,  384996.1875,  285276.2500,  176985.2969,
         142668.8594,  128283.6250,  102557.4609,   94473.4297,   88912.4375],
       device='cuda:0')
['stands' 'crafts' 'devices' 'desk' 'furniture' 'portable' 'helping'
 'chairs' 'tables' 'laptops']

For Feature 7131
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0229, 0.0215, 0.0168, 0.0159, 0.0146, 0.0132, 0.0126, 0.0116, 0.0101,
        0.0090], device='cuda:0')
['issue' 'tripadvisor' 'duty' 'poster' 'organization' 'front' 'covers'
 'boards' 'sheet' 'doors']

Most Changed, by Ratio Over 160 Images:
tensor([2510017.0000,  844383.1875,  409233.2188, 


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.1653, 0.1277, 0.0706, 0.0416, 0.0406, 0.0342, 0.0192, 0.0147, 0.0138,
        0.0132], device='cuda:0')
['benefit' 'laser' 'picks' 'quarter' 'jennifer' 'pioneer' 'pick' 'date'
 'converter' 'johnson']

Most Changed, by Ratio Over 160 Images:
tensor([1928054.8750,  719520.4375,  379859.0625,  340585.2500,  233419.9219,
         198928.3594,  166998.2969,  127715.3125,   86025.7578,   83148.1250],
       device='cuda:0')
['benefit' 'picks' 'arkansas' 'lingerie' 'quarter' 'label' 'dates' 'roses'
 'connecticut' 'jennifer']

For Feature 253
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0379, 0.0374, 0.0326, 0.0243, 0.0191, 0.0178, 0.0173, 0.0169, 0.0163,
        0.0160], device='cuda:0')
['inter' 'greek' 'philips' 'italian' 'bar' 'advertisement' 'trembl'
 'bulgaria' 'parliament' 'russian']

Most Changed, by Ratio Over 160 Images:
tensor([2518521.7500, 1355185.8750,  87052


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0496, 0.0423, 0.0327, 0.0311, 0.0208, 0.0182, 0.0175, 0.0149, 0.0143,
        0.0134], device='cuda:0')
['text' 'thumbnail' 'used' 'brand' 'title' 'type' 'ha' 'tip' 'patch'
 'front']

Most Changed, by Ratio Over 160 Images:
tensor([1420786.3750,  817368.4375,  452899.0625,  247230.7500,  165247.1250,
         141098.0156,  129603.3984,  115070.6797,  113882.2266,  103913.1484],
       device='cuda:0')
['cumshot' 'text' 'aug' 'purple' 'gonna' 'michigan' 'phones' 'flowers'
 'alabama' 'recipes']

For Feature 23970
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.3717, 0.1528, 0.0487, 0.0296, 0.0269, 0.0187, 0.0113, 0.0102, 0.0102,
        0.0099], device='cuda:0')
['posters' 'page' 'publication' 'poster' 'certificates' 'scan' 'magazines'
 'files' 'magazine' 'pages']

Most Changed, by Ratio Over 160 Images:
tensor([37450792.0000,  1068497.8750,   926678.8125,   882399.6875


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.3501, 0.0155, 0.0144, 0.0099, 0.0083, 0.0077, 0.0072, 0.0072, 0.0070,
        0.0057], device='cuda:0')
['african' 'africa' 'providing' 'group' 'resource' 'council' 'dish'
 'figure' 'image' 'site']

Most Changed, by Ratio Over 160 Images:
tensor([510739.5938, 402496.8438, 274142.0625, 252717.2344, 206794.2344,
        197991.1094, 197163.0156, 190315.8750, 178354.9844, 147155.9062],
       device='cuda:0')
['african' 'businesses' 'vehicles' 'children' 'shirts' 'agriculture'
 'volunteers' 'building' 'village' 'africa']

For Feature 9407
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.0278, 0.0219, 0.0193, 0.0160, 0.0143, 0.0112, 0.0106, 0.0089, 0.0086,
        0.0081], device='cuda:0')
['obtain' 'shown' 'configuration' 'sets' 'lot' 'contains' 'los' 'listing'
 'sizes' 'rentals']

Most Changed, by Ratio Over 160 Images:
tensor([1729379.6250,  474984.8438,  299951.4062,  


Most Changed, by Absolute Diff Over 160 Images:
tensor([0.1174, 0.0643, 0.0307, 0.0279, 0.0272, 0.0256, 0.0256, 0.0241, 0.0193,
        0.0168], device='cuda:0')
['y' 'boot' 'video' 'shoe' 'v' 'hair' 'counties' 'header' 'shoes' 'boat']

Most Changed, by Ratio Over 160 Images:
tensor([3590041.2500, 3509934.7500, 1007940.8125,  563603.6250,  551947.3125,
         443550.1562,  437962.7188,  320837.7500,  302204.0938,  225259.8281],
       device='cuda:0')
['counties' 'boats' 'hair' 'boat' 'trees' 'header' 'pants' 'road' 'shoes'
 'street']

For Feature 38644
text_probs_altered shape: torch.Size([160, 5000])

Most Changed, by Absolute Diff Over 160 Images:
tensor([0.5977, 0.2320, 0.0083, 0.0077, 0.0062, 0.0051, 0.0027, 0.0025, 0.0018,
        0.0015], device='cuda:0')
['washington' 'dc' 'president' 'button' 'constitution' 'clinton'
 'congress' 'representative' 'dildo' 'buttons']

Most Changed, by Ratio Over 160 Images:
tensor([7965256.0000,  773426.1250,  144078.8281,  101094.4609,   5814

In [17]:
steering_strength_image_results.keys(), steering_strength_image_results[str(steering_strength)].keys()

(dict_keys(['0.0', '5.0', '10.0', '20.0', '50.0', '150.0']),
 dict_keys([26600, 8518, 16347, 46981, 44837, 41588, 46158, 30052, 36177, 17551, 35377, 41389, 12950, 7623, 48170, 1527, 22666, 45420, 36780, 38339, 22534, 32663, 2032, 7697, 23439, 18977, 1366, 36950, 44476, 9108, 42357, 33482, 2874, 24884, 17589, 21462, 561, 5473, 9246, 7131, 21158, 13913, 2705, 21193, 1807, 48735, 25174, 13982, 26171, 4525, 2722, 31039, 31221, 9728, 5823, 253, 24617, 20914, 30159, 14840, 3193, 2490, 39796, 31782, 33170, 4333, 26182, 23970, 21597, 3031, 15968, 5767, 45594, 47466, 34121, 18305, 7995, 42826, 19049, 9407, 3818, 47779, 44957, 40803, 41756, 38695, 38400, 34131, 17558, 43847, 38820, 38644, 17816, 44636, 3900, 43524, 1404, 35344, 39478, 26052]))

In [18]:
i = 0

# 0: python, 3: bowl, 4: bed, 6: guinea
image_idx = 0


feat_num = 31664#list(steering_strength_image_results[str(steering_strength)].keys())[-2]

# to iterate over many features:
# for feat_num in steering_strength_image_results[str(steering_strength)].keys():

print(f"=====================\nfeat_num: {feat_num}")
feat_num_concept_arr = []
feat_num_prob_arr = []
for dict_key in steering_strengths:
    # image, tuple position, idx of top-k
    feat_num_concept_arr.append((dict_key, steering_strength_image_results[str(dict_key)][feat_num][image_idx][0][0]))
#     print(str(dict_key), steering_strength_image_results[str(dict_key)][feat_num][image_idx][0][0])
    feat_num_prob_arr.append((dict_key, steering_strength_image_results[str(dict_key)][feat_num][image_idx][1][0].item()))
#     print(str(dict_key), steering_strength_image_results[str(dict_key)][feat_num][image_idx][1][0].item())


feat_num: 31664


KeyError: 31664

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Sample data
x = [tup[0] for tup in sorted(feat_num_concept_arr)]
y1 = [tup[1] for tup in sorted(feat_num_concept_arr)]
y2 = [tup[1] for tup in sorted(feat_num_prob_arr)]

# Create the plot
plt.figure(figsize=(10, 6))

# Plot each line with different colors and markers
plt.plot(np.array(x), y2, 'rs-', label='Prob, Label at Strength')  # Red line with squares

# Label each point
for i in range(len(x)):
    # Labels for series
    plt.annotate(f'({y2[i]:01f}, {y1[i]})', 
                (x[i], y2[i]), 
                textcoords="offset points", 
                xytext=(0,-15),
                ha='center')
    
# Customize the plot
plt.xlabel('Feature Steering Strength (feat = Strength)')
plt.ylabel('Probability of TPL, Top Predicted Label')
plt.title(f'Most Likely Class by Feature Steering Strength, Feature {feat_num}\n Label at 0.0: {steering_strength_image_results[str(0.0)][feat_num][image_idx][0][0]}. Label at max steered val ({str(max(steering_strengths))}): {steering_strength_image_results[str(max(steering_strengths))][feat_num][image_idx][0][0]}.')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)

# Adjust layout to prevent label overlap
plt.tight_layout()


# plt.savefig("test.svg")

# Show the plot
plt.show()

In [ ]:
# top-k logits chart
# i = 10
# 0: python, 3: bowl, 4: bed, 6: guinea
image_idx = image_idx
feat_num = feat_num

# to iterate over many features:
# for feat_num in steering_strength_image_results[str(steering_strength)].keys():

print(f"=====================\nfeat_num: {feat_num}")
feat_num_concept_arr = []
feat_num_concept_arr_2 = []
feat_num_concept_arr_3 = []
feat_num_prob_arr = []
feat_num_prob_arr_2 = []
feat_num_prob_arr_3 = []
for dict_key in steering_strengths:
    # image, tuple position, idx of top-k
    # modify this to do top-k at some point
#     print(str(dict_key), steering_strength_image_results[str(dict_key)][feat_num][image_idx][0][0])
    feat_num_concept_arr.append((dict_key, steering_strength_image_results[str(dict_key)][feat_num][image_idx][0][0]))
    feat_num_concept_arr_2.append((dict_key, steering_strength_image_results[str(dict_key)][feat_num][image_idx][0][1]))
    feat_num_concept_arr_3.append((dict_key, steering_strength_image_results[str(dict_key)][feat_num][image_idx][0][2]))
#     print(str(dict_key), steering_strength_image_results[str(dict_key)][feat_num][image_idx][1][0].item())
    feat_num_prob_arr.append((dict_key, steering_strength_image_results[str(dict_key)][feat_num][image_idx][1][0].item()))
    feat_num_prob_arr_2.append((dict_key, steering_strength_image_results[str(dict_key)][feat_num][image_idx][1][1].item()))
    feat_num_prob_arr_3.append((dict_key, steering_strength_image_results[str(dict_key)][feat_num][image_idx][1][2].item()))


# Sample data
x = [tup[0] for tup in sorted(feat_num_concept_arr)]
y1 = [tup[1] for tup in sorted(feat_num_concept_arr)]
y2 = [tup[1] for tup in sorted(feat_num_prob_arr)]
y1_2 = [tup[1] for tup in sorted(feat_num_concept_arr_2)]
y2_2 = [tup[1] for tup in sorted(feat_num_prob_arr_2)]
y1_3 = [tup[1] for tup in sorted(feat_num_concept_arr_3)]
y2_3 = [tup[1] for tup in sorted(feat_num_prob_arr_3)]

# Create the plot
plt.figure(figsize=(15, 9))

# Plot each line with different colors and markers
plt.plot(np.array(x), y2, 'rs-', label='Prob, Label at Strength')  # Red line with squares
plt.plot(np.array(x), y2_2, 'ms-', label='Prob, Label at Strength')  # Red line with squares
plt.plot(np.array(x), y2_3, 'ys-', label='Prob, Label at Strength')  # Red line with squares

# Label each point
for i in range(len(x)):
    # Labels for series
    plt.annotate(f'({y2[i]:01f}, {y1[i]})', 
                (x[i], y2[i]), 
                textcoords="offset points", 
                xytext=(0,-15),
                ha='center')
    plt.annotate(f'({y2_2[i]:01f}, {y1_2[i]})', 
                (x[i], y2_2[i]), 
                textcoords="offset points", 
                xytext=(0,-15),
                ha='center')
    plt.annotate(f'({y2_3[i]:01f}, {y1_3[i]})', 
                (x[i], y2_3[i]), 
                textcoords="offset points", 
                xytext=(0,-15),
                ha='center')
    
# Customize the plot
plt.xlabel('Feature Steering Strength (feat = Strength)')
plt.ylabel('Probability of TPL, Top Predicted Label')
plt.title(f'Most Likely Class by Feature Steering Strength, Feature {feat_num}\n Label at 0.0: {steering_strength_image_results[str(0.0)][feat_num][image_idx][0][0]}. Label at max steered val ({str(max(steering_strengths))}): {steering_strength_image_results[str(max(steering_strengths))][feat_num][image_idx][0][0]}.')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)

# Adjust layout to prevent label overlap
plt.tight_layout()


# plt.savefig("test.svg")

# Show the plot
plt.show()

In [ ]:
steering_strength_info.keys()

In [ ]:
# Steerability metric
# print topk steerability

for feat_num in steering_strength_image_results[str(steering_strength)].keys():
    feat_num_steerability = feat_num
    # steering_strength_info[steering_strength] = (top_concep,top_val,aggregate_ratio,aggregate_diff)
    agg_diff_arr = []
    steerability_arr = []
    i = 0
    for key in steering_strength_info:
    #     print(key, steering_strength_info[key][4][feat_num].cpu())
        steerability_arr.append(steering_strength_info[key][4][feat_num_steerability].sum().cpu().item())
        agg_diff_arr.append(steering_strength_info[key][3][feat_num_steerability].cpu().item())
    #     agg_diff_arr.append(steering_strength_info[key][2][feat_num_steerability].cpu().item())
    #     i += 1
    #     if i > 3:
    #         agg_diff_arr[-1] = agg_diff_arr[-2]

    import matplotlib.pyplot as plt
    import numpy as np

    # Sample data
    x = [tup[0] for tup in sorted(feat_num_concept_arr)]
    y1 = agg_diff_arr
    y2 = steerability_arr

    # Create the plot
    plt.figure(figsize=(10, 6))

    # Plot each line with different colors and markers
    plt.plot(np.array(x), y1, 'rs-', label='Strength, Aggregate Probability Difference')  # Red line with squares
    plt.plot(np.array(x), y2, 'ms-', label='Strength, Steerability Score')  # Red line with squares

    # Label each point
    for i in range(len(x)):
        # Labels for series
        plt.annotate(f'({x[i]:.1f}, {y1[i]:.3f})', 
                    (x[i], y1[i]), 
                    textcoords="offset points", 
                    xytext=(0,-15),
                    ha='center')
        plt.annotate(f'({x[i]:.1f}, {y2[i]:.3f})', 
                    (x[i], y2[i]), 
                    textcoords="offset points", 
                    xytext=(0,-15),
                    ha='center')

    # Customize the plot
    plt.xlabel('Feature Steering Strength (feat = Strength)')
    plt.ylabel('Sum of Probability Difference Over All Tested Images')
    plt.title(f'Aggregate Probability Difference at different steering strengths, Feature {feat_num_steerability}')
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.7)

    # Adjust layout to prevent label overlap
    plt.tight_layout()


    # plt.savefig("test.svg")

    # Show the plot
    plt.show()
    # image, tuple position, idx of top-k
    print(feat_num)
    print(dict_key, steering_strength_image_results[str(dict_key)][feat_num][image_idx][0])
    print(dict_key, "probs", steering_strength_image_results[str(dict_key)][feat_num][image_idx][1])
    print(steering_strength_info[150.0][4][feat_num_steerability].shape)
    vals, idxs = torch.topk(steering_strength_info[150.0][5][feat_num_steerability].cpu(), k=10)
    print("probabilities * abs(probabilities)", vals)
    print(np.array(selected_vocab)[idxs.cpu()])
    

In [ ]:
# SAE steering power and specificity metrics:

sae_asps = []
sae_asy_str_specs = []
sae_asrs = []
for feat_num in steering_strength_image_results[str(steering_strength)].keys():
    feat_num_steerability = feat_num
    
    asymptote_key = max([float(key) for key in steering_strength_info.keys()])
    asymptotic_steering_specificity = steering_strength_info[asymptote_key][4][feat_num_steerability].sum().cpu().item()
    asymptotic_steering_power = steering_strength_info[asymptote_key][3][feat_num_steerability].cpu().item()
    print(f"feat: {feat_num_steerability}")
    print(f"asymptotic_steering_specificity: {asymptotic_steering_specificity}")
    print(f"asymptotic_steering_power: {asymptotic_steering_power}")
    print(f"asymptotic_steering_power percent: {(asymptotic_steering_power * 100):.2f}%")
    print(f"specificity/power: {asymptotic_steering_specificity/asymptotic_steering_power}")
    
    sae_asps.append(asymptotic_steering_power)
    sae_asy_str_specs.append(asymptotic_steering_specificity)
    sae_asrs.append(asymptotic_steering_specificity/asymptotic_steering_power)

print(f"\nSAE: {selected_sae_weights}")
print(f"\nSAE avg power: {np.array(sae_asps).mean()}")
print(f"SAE avg specificity: {np.array(sae_asy_str_specs).mean()}")
print(f"SAE avg s/p ratio: {np.array(sae_asrs).mean()}")
plt.figure(figsize=(5, 3))
plt.hist(sae_asps, bins=100)
plt.show()

plt.figure(figsize=(5, 3))
plt.hist(sae_asy_str_specs, bins=100)
plt.show()

plt.figure(figsize=(5, 3))
plt.hist(sae_asrs, bins=100)
plt.show()

### Prev Code

In [278]:
len(feature_steered_embeds[random_feat_idxs[0]])

32

In [279]:
default_embeds.shape
len(default_embeds_list)
default_embeds = torch.cat(default_embeds_list)
default_embeds.shape

torch.Size([32, 512])

In [280]:

len(altered_embeds_list), altered_embeds_list[0].shape, default_embeds.shape

(10, torch.Size([32, 512]), torch.Size([32, 512]))

In [281]:
og_model.cuda()

CLIP(
  (visual): VisionTransformer(
    (conv1): Conv2d(3, 768, kernel_size=(32, 32), stride=(32, 32), bias=False)
    (patch_dropout): Identity()
    (ln_pre): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (transformer): Transformer(
      (resblocks): ModuleList(
        (0-11): 12 x ResidualAttentionBlock(
          (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=768, out_features=768, bias=True)
          )
          (ls_1): Identity()
          (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (mlp): Sequential(
            (c_fc): Linear(in_features=768, out_features=3072, bias=True)
            (gelu): GELU(approximate='none')
            (c_proj): Linear(in_features=3072, out_features=768, bias=True)
          )
          (ls_2): Identity()
        )
      )
    )
    (ln_post): LayerNorm((768,), eps=1e-05, elementwise_affine

In [282]:
with open("/workspace/clip_dissect_raw.txt", "r") as f:
    larger_vocab = [line[:-1] for line in f.readlines()][:5000]

# with open("/workspace/better_img_desc.txt", "r") as f:
#     larger_vocab = [line[:-1] for line in f.readlines()][:5000]

In [283]:
# use clip vocab here and compare embeds
import torch
from PIL import Image

tokenizer = open_clip.get_tokenizer('ViT-B-32')
text = tokenizer(larger_vocab)
text_features = og_model.encode_text(text.cuda())
text_features_normed = text_features/text_features.norm(dim=-1, keepdim=True)


print(f"text_features_normed.shape: {text_features_normed.shape}")
text_probs_altered_list = []
with torch.no_grad(), torch.cuda.amp.autocast():
    for key in feature_steered_embeds:
        print(key)
        # embeds already have L2 norm of 1
        text_probs_altered = (100.0 * torch.stack(feature_steered_embeds[key]) @ text_features_normed.T).softmax(dim=-1)
        text_probs_altered_list.append(text_probs_altered)
    text_probs_default = (100.0 * default_embeds @ text_features_normed.T).softmax(dim=-1)

print("Label probs altered:", text_probs_altered.shape)  # prints: [[1., 0., 0.]]
print("Label probs default:", text_probs_default.shape)  # prints: [[1., 0., 0.]]

text_features_normed.shape: torch.Size([5000, 512])
655
656
665
2541
9482
21803
21701
22826
17981
10559
Label probs altered: torch.Size([32, 5000])
Label probs default: torch.Size([32, 5000])


### Summed Logit Difference

In [ ]:
# subtract from default, label, and print trends
text_probs_altered.shape

# selected_vocab = all_imagenet_class_names
selected_vocab = larger_vocab

top_concept_per_feat = {}
top_val_per_feat = {}
top_diff_per_feat = {}
top_ratio_per_feat = {}
# run this for sampled features over all of imagenet eval
for j, text_probs_altered in enumerate(text_probs_altered_list):
    print(f"{'============================================'*2}\n\nFor Feature {random_feat_idxs[j]}")
    print("actual image content:")
    default_vals_softmax, default_idxs_softmax = torch.topk(text_probs_default,k=10)
    print(default_vals_softmax, "\n", np.array(selected_vocab)[default_idxs_softmax.cpu()])
    
    
    logit_diff = text_probs_altered - text_probs_default
    logit_diff_aggregate = logit_diff.sum(dim=0)
    
    logit_ratio = text_probs_altered/text_probs_default
    logit_ratio_aggregate = logit_ratio.mean(dim=0)
    
    print(f"text_probs_altered.softmax(): {text_probs_altered.softmax(1).shape}")
    text_probs_altered_softmax = text_probs_altered.softmax(1)
    vals_softmax, idxs_softmax = torch.topk(text_probs_altered_softmax,k=10)
    
#     print(f"text_probs_altered.softmax(): {text_probs_altered.sum(0).softmax(0).shape}")
#     text_probs_altered_softmax_agg = text_probs_altered.sum(0).softmax(0)
#     vals_softmax_agg, idxs_softmax_agg = torch.topk(text_probs_altered_softmax_agg,k=10)
    
    print(f"\nSoftmax Over {text_probs_altered.shape[0]} Images:\n{vals_softmax}")
    print(np.array(selected_vocab)[idxs_softmax.cpu()])
    for i in range(vals_softmax.shape[0]):
        print(vals_softmax[i], "\n", np.array(selected_vocab)[idxs_softmax.cpu()][i])
        break
        
#     print(f"\nAgg Softmax Over {text_probs_altered.shape[0]} Images:\n{vals_softmax_agg}")
#     print(np.array(selected_vocab)[idxs_softmax_agg.cpu()])
    
    vals_agg, idxs_agg = torch.topk(logit_diff_aggregate,k=10)
    vals_least_agg, idxs_least_agg = torch.topk(logit_diff_aggregate,k=10,largest=False)
    
    ratios_agg, ratios_idxs_agg = torch.topk(logit_ratio_aggregate,k=10)
    ratios_least_agg, ratios_idxs_least_agg = torch.topk(logit_ratio_aggregate,k=10,largest=False)
    
    vals, idxs = torch.topk(logit_diff,k=5)
    vals_least, idxs_least = torch.topk(logit_diff,k=5,largest=False)
    
    ratios, ratios_idxs = torch.topk(logit_ratio,k=5)
    ratios_least, ratios_idxs_least = torch.topk(logit_ratio,k=5,largest=False)
    
    top_concept_per_feat[random_feat_idxs[j]] = np.array(selected_vocab)[idxs_softmax.cpu()][0][0]
    top_val_per_feat[random_feat_idxs[j]] = vals_softmax[0][0]
    top_diff_per_feat[random_feat_idxs[j]] = vals_agg[0]
    top_ratio_per_feat[random_feat_idxs[j]] = ratios_agg[0]
    
    
    print(f"\nMost Changed, by Absolute Diff Over {logit_diff.shape[0]} Images:\n{vals_agg}")
    print(np.array(selected_vocab)[idxs_agg.cpu()])
    print(vals_least_agg)
    print(np.array(selected_vocab)[idxs_least_agg.cpu()])
    
    print(f"\nMost Changed, by Ratio Over {logit_diff.shape[0]} Images:")
    print(ratios_agg)
    print(np.array(selected_vocab)[ratios_idxs_agg.cpu()])
    print(vals_least_agg)
    print(np.array(selected_vocab)[ratios_idxs_least_agg.cpu()])

In [ ]:
top_concept_per_feat,top_val_per_feat,top_ratio_per_feat

In [ ]:
steering_strength_info = {}
steering_strength_info[steering_strength] = (top_concept_per_feat,top_val_per_feat,top_ratio_per_feat,top_diff_per_feat)


In [ ]:
steering_strength_info[steering_strength][0].keys()

In [ ]:
steering_strength_info

In [ ]:
i = 0
for feat_num in steering_strength_info[steering_strength][0].keys():
    print(f"=====================\nfeat_num: {feat_num}")
    feat_num_concept_arr = []
    feat_num_prob_arr = []
    feat_num_ratio_arr = []
    for key in steering_strength_info:
        print(key, steering_strength_info[key][0][feat_num])
        feat_num_concept_arr.append((key, steering_strength_info[key][0][feat_num]))
        print(key, steering_strength_info[key][1][feat_num])
        feat_num_prob_arr.append((key, steering_strength_info[key][1][feat_num].item()))
        print(key, steering_strength_info[key][2][feat_num])
        feat_num_ratio_arr.append((key, steering_strength_info[key][2][feat_num].item()))
    i += 1
    if i > 5:
        break

In [ ]:
sorted(feat_num_concept_arr),sorted(feat_num_prob_arr),sorted(feat_num_ratio_arr),

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Sample data
x = [tup[0] for tup in sorted(feat_num_concept_arr)]
y1 = [tup[1] for tup in sorted(feat_num_concept_arr)]
y2 = [tup[1] for tup in sorted(feat_num_prob_arr)]
# y3 = [tup[1] for tup in sorted(feat_num_ratio_arr)]

# Create the plot
plt.figure(figsize=(10, 6))

# Plot each line with different colors and markers
# plt.plot(x, y1, 'bo-', label='Series 1')  # Blue line with circles
plt.plot(np.array(x), y2, 'rs-', label='Series 2')  # Red line with squares
# plt.plot(x, y3, 'gd-', label='Series 3')  # Green line with diamonds

# Label each point for all three series
for i in range(len(x)):
#     # Labels for series 1
#     plt.annotate(f'({x[i]}, {y1[i]})', 
#                 (x[i], y1[i]), 
#                 textcoords="offset points", 
#                 xytext=(0,10),
#                 ha='center')
    
    # Labels for series 2
    plt.annotate(f'({y2[i]:01f}, {y1[i]})', 
                (x[i], y2[i]), 
                textcoords="offset points", 
                xytext=(0,-15),
                ha='center')
    
#     # Labels for series 3
#     plt.annotate(f'({x[i]}, {y3[i]})', 
#                 (x[i], y3[i]), 
#                 textcoords="offset points", 
#                 xytext=(0,10),
#                 ha='center')

# Customize the plot
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title(f'Most Likely Class by Feature Steering Strength, Feature {feat_num}\n Label at 0.0: {steering_strength_info[0.0][0][feat_num]}. Label at max steered val: {steering_strength_info[max(list(steering_strength_info.keys()))][0][feat_num]}.')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)

# Adjust layout to prevent label overlap
plt.tight_layout()

# Show the plot
plt.show()

## Enc/Dec Clustering/Exploration

In [ ]:
encoder_weights_for_math = sparse_autoencoder.W_enc
decoder_weights_for_math = sparse_autoencoder.W_dec

In [ ]:
dists_from_feat_0 = encoder_weights_for_math[0] - encoder_weights_for_math

In [ ]:
dists_from_feat_0_normalized = encoder_weights_for_math[0]/encoder_weights_for_math[0].norm(p=2) - encoder_weights_for_math/encoder_weights_for_math.norm(p=2,dim=0)

In [ ]:
dists_from_feat_0.norm(p=2, dim=0).shape

In [ ]:
# plt.hist(bins[:-1], bins)
plt.hist(dists_from_feat_0.norm(p=2, dim=0).cpu(), density=True, bins=1000, histtype='step')  # density=False would make counts
plt.title('Encoder Dist from feat 0')
plt.ylabel('L2 Distance')
plt.xlabel('Density (of ~50k feats)');


In [ ]:
torch.topk(dists_from_feat_0.norm(p=2, dim=0),k=10,largest=False)

In [ ]:
dec_dists_from_feat_0 = decoder_weights_for_math[0]/decoder_weights_for_math[0].norm(p=2) - decoder_weights_for_math/decoder_weights_for_math.norm(p=2)
dec_dists_from_feat_0.shape

In [ ]:
# plt.hist(bins[:-1], bins)
plt.hist(dec_dists_from_feat_0.T.norm(p=2, dim=0).cpu(), density=True, bins=1000, histtype='step')  # density=False would make counts
plt.title('Decoder Dist from feat 0')
plt.ylabel('L2 Distance')
plt.xlabel('Density (of ~50k feats)');


In [ ]:
torch.topk(dec_dists_from_feat_0.T.norm(p=2, dim=0),k=10,largest=False)

In [ ]:
dec_dists_from_feat_0.T.norm(p=2, dim=0).shape